### ISSUE TITLE
Support for packages installation from renv.lock file

### ISSUE THREAD

**Issue by GitHunter0** [eddelbuettel/littler#100]
Hi folks, do you have plans to support packages installation from a `renv.lock` file (created by `renv` package)?

This would be really useful to create docker images reproducing the specified environment. 

If you are familiar to Python, it would be similar to `install -r requirements.txt` and `conda env create -f environment.yml`

Currently we have to manually check the list and type the packages one by one, or create and configure a `renv` project inside docker (and then use `renv::install()`), however this approach is messy and hard to make it work properly in my experience.

Thank you

**Comment by eddelbuettel** [comment]
I don't seen how that is a concern or huge case for `littler`, but maybe that is due to me not using `renv` and not believing in such locked environments (as I updated my packages directly).

But by all means do feel free to write such a function and maybe blog about it.  Good luck!

**Comment by eddelbuettel** [comment]
Also, see this recent(-ish) tweet by Kevin -- methinks there must be a function in there for installing from a lockfile.  Among _1245_ functions one surely does this.

![image](https://user-images.githubusercontent.com/673121/157370400-617d0d64-b379-4cb7-91f2-839da5474ca6.png)

**Comment by GitHunter0** [comment]
Thank you, hopefully I will find a function that implements that.

**Comment by eddelbuettel** [comment]
I would think so. I have a few friends who really like `renv` and installation from a stored lockfile is, as far as I can tell as a non-user of the package, and existing feature.
