### ISSUE TITLE
The best approach to include the package version in install2.r function 

### ISSUE THREAD

**Issue by Naeemkh** [eddelbuettel/littler#102]
Thanks for the `littler` package. 
I use `install2.r` function inside a Dockerfile on top of `The Rocker Project` images. I was wondering if there is any recommended way to include a version in installing the packages?

It seems one way could be installing form mran, according to the following:
```
RUN install2.r --error --repo https://mran.microsoft.com/snapshot/2022-05-23 \
```
However, not sure if it is the best way. Could you please let me know your thoughts? Thanks.

**Comment by eddelbuettel** [comment]
There is not because R (as in Base R, and CRAN) does not _natively_ support this.  By default the most recent versions are used.  So  that is what we support.

You could write yourself a variant `installVersion.r` that, say, reads the Archive/ directory for a package.  _But you will have absolutely no guarantee about matching versions of dependencies_ so to me this is a non-starter.

MRAN used to installation-by-date, and RSPM does something like that.  I wrote a `installRSPM.r` too, maybe you want to play around with it and with date setting?

**Comment by Naeemkh** [comment]
Thanks, @eddelbuettel!

**Comment by eddelbuettel** [comment]
You _could_ try to play with it.  I think you would to 'crawl up one layer' and make `available.packages()` and alike consume the dated information (also for any dependencies).  That should in a first pass be able to fill, say, an empty VM or Docker container or new machine.   The problem of possibly downgrade currrent packages to the date you pick strikes me as the elephant in the room.   

But no reason not to experiment so let us know how it goes if you venture there!

**Comment by eddelbuettel** [comment]
I actually noticed the other day that one of the `debhelper` (or was it `remotes` ?) functions has a versioned install which seemingly takes a package name and a version and feeds that along.  We could probably wrap that up in a small helper script.

**Comment by eddelbuettel** [comment]
I would generally discourage this and warn against it. It may work for you (and me) but more general user may get confused about library versioning of they attempt this time travel.

In any event, R is at 4.2.1 and that is what I recommend and use -- and current versions are what `install.r` and `install2.r` were written for.  I have a trial ballon helper script `installRSPM.r`; you could may play with adding a target daye there.

I'll close this now as the desired functionality of the initial post simply is not available.

**Comment by Fredo-XVII** [comment]
I wish I could use 4.2.1, but at work I am constrained to 4.0.2 as I don't have access to make changes on the platform.  I will take a look at installRSPM.r and see how I can leverage that. 

Thanks!

**Comment by eddelbuettel** [comment]
I hear you, and I had worse / similar constraints. You'll have to be creative and see what you can do -- docker can help.  But keep in mind that bug reports have to be for _current_ deployments.  Thank you for your understanding.
