### ISSUE TITLE
install2.r requires RCurl as a dependency

### ISSUE THREAD

**Issue by Fredo-XVII** [eddelbuettel/littler#106]
Hello!

So I am using Rocker/tidyverse:4.0.2 docker image to build my solution, which comes with `littler`. I first install the Linux dependencies that I need, then I install the R packages that I need, that are not installed by the Rocker image.  In doing this work, I noticed the behavior below.  

In summary, if I lead with any package other than `RCurl`, `install2.r` seems to fail.  If I lead with `RCurl`, works like a charm.  I don't know if this is a Rocker image build issue, but it seem to me that I should start here.  If this is not an issue, please close this, but a warning that `RCurl` should come first would be nice.

Notice the row number at the top 2545, everything above is the same and unchanged between runs.

Fail Code:
```
      install2.r --error --skipmissing TRUE --deps TRUE --skipinstalled TRUE -n \
        -r 'https://packagemanager.rstudio.com/all/__linux__/focal/2020-10-09+Y3JhbiwyOjI4Nzs0MTRBMjc2QQ' \
        rJava \
        RCurl \
        etc...\
 ```       

Fail Output:

![image](https://user-images.githubusercontent.com/8800540/191545797-237b5d55-d48a-41bd-a77e-e1d84341db1c.png)

Successful Code:
```
      install2.r --error --skipmissing TRUE --deps TRUE --skipinstalled TRUE -n \
        -r 'https://packagemanager.rstudio.com/all/__linux__/focal/2020-10-09+Y3JhbiwyOjI4Nzs0MTRBMjc2QQ' \
        RCurl \
        rJava \
        etc... \
 ```       

Successful Output:

![image](https://user-images.githubusercontent.com/8800540/191546206-c19c8217-8d5c-4595-97c5-7523880edffc.png)

**Comment by eddelbuettel** [comment]
False, or I should say 'only true in a long outdated version' you still use.  Which is not relevant for bug reports today.

R itself now builds with and uses `libcurl`.

**Comment by eitsupi** [comment]
@Fredo-XVII `--skipmissing` is an option that does not exist in `install2.r` shipped with `littler`.
And, `install2.r` does not install the given packages in order.

I suspect that this is a bug in `docopt` and that it only happens to work if the RCurl is the first one under some influence even though it specifies an option that does not exist.

In any case, it has nothing to do with this repository, so if the problem still exists, I suggest you submit it to https://github.com/rocker-org/rocker-versioned2.

**Comment by eddelbuettel** [comment]
Also, R itself switches a few releases ago to using `libcurl` more, see `help(download.file)` and the 'Details' and 'Note'. Also:


```r
> capabilities("libcurl")
libcurl 
   TRUE 
> 
```

which was added a major release or two ago.
