### ISSUE TITLE
howto use configure --program-prefix="l"

### ISSUE THREAD

**Issue by mostly-harmless** [eddelbuettel/littler#11]
I would like to try out `littler` on a mac

There is no script called `configure` in the littler repo so I am not sure how to do:

`./configure --program-prefix="l"`

What am I missing? Thanks

**Comment by eddelbuettel** [comment]
##### Case One: You work from git

The script `configure` is created by running the script `bootstrap` which contains towards the bottom:

```{bash}
test -f gitversion.h || call_gitversion
aclocal 
autoheader 
automake 
autoconf 
./configure 
make
```

You could either modify `bootstrap` to add the arguments you want, or re-run after it create the `r` you do not want.

##### Case Two: You work from a release tarball

The tarball contains `configure`.

##### See file `INSTALL`

This is all detailed in `INSTALL` -- but do let me know if something is missing etc.

**Comment by mostly-harmless** [comment]
Thank you for the pointer to the INSTALL file. I was following the instructions in the README.md file but misunderstood the reference to bootstrap. I tried updating the ./configure line in bootstrap and rerunning ./configure after bootstrap (followed by make). Both produced `r` in the littler directory but not the alternatively named version. I also tried using a suffix but no luck.

**Comment by eddelbuettel** [comment]
Ok -- let me know how it goes, and how I could make it better. I *definitely* wants this to work on OS X given [the usual joke](https://twitter.com/bigdataborat/status/372350993255518208).

**Comment by mostly-harmless** [comment]
It doesn't (go). But then I am on a mac :) See previous comment. I cannot get the ./configure options (followed by make) to produce `lr`, `littler` or any other name. I tried with "" around the prefix (as suggested in the README) and without quotes (as suggested in INSTALL). Configure does update the Makefile with information about the name to use for the build but doesn't seem to use it. I am assuming there should be a file in littler/ with the name `myprenamer` but there is only `r`

program_transform_name = s&$$&mypostname&
program_transform_name = s&^&myprename&

I just tried compiling from source on unbuntu with the same result (i.e., prefix is ignored). Any suggestions would be welcome. Thanks

On a side note ... If 'datascience is statistics on a mac' what is datascience on windows?

**Comment by eddelbuettel** [comment]
Darn. It did work an some point. I may have reworked the autotools logic after that.

I'll reopen and leave it open.

**Comment by eddelbuettel** [comment]
As a start, can you build locally, and just install the result `r` as `/usr/local/bin/lr` (or some other name)?

**Comment by eddelbuettel** [comment]
I always get confused by this. Follow the `Makefile`, the business about `transform` happens only when you run `make install`.  So please try that.

**Comment by mostly-harmless** [comment]
It works! I was hesitant to use `make install` because it wasn't clear to me if it might mess-up the regular R install. `make install` did use the name prefix however to create `lr`. Nice.

I tried `brew install littler` on my office machine (Mavericks) but got a message there was no formula. On my laptop (Yosemite) it did find one however and it installed as `littler`. I added a shortcut to `lr` for convenience. Perhaps you would consider mentioning the `brew` option for mac users in the install instructions?

Thanks!

**Comment by eddelbuettel** [comment]
Glad to know it works.

I have no interaction with whoever coordinates the brew builds. Maybe you could follow up?

I'll leave with open as a reminder to stress `make install` as a finishing step.

**Comment by eddelbuettel** [comment]
Ok, pushed another commit with a comment on this. The (very old) `README` (ie not the .md variant) also had it.  So closing this now :)

**Comment by mostly-harmless** [comment]
Thanks Dirk. I will try to figure out what is going on with the brew setup.


—

**Comment by mostly-harmless** [comment]
Got littler installed on my office mac as well. It seem you need to add a repo find the formula for littler. The following should work:

brew tap homebrew/science
brew install littler

This will install littler as `littler

http://brew.sh/

**Comment by eddelbuettel** [comment]
Thank you for this.  I may add this to the docs.

It was my understanding, though, that the overall recommendation was to not use R from brew, but rather rely on Simon's packages from the ATT site.  Which R is this littler binary built against?

**Comment by mostly-harmless** [comment]
Yeah I think this might not be a good idea at the moment. Both on my laptop and on desktop Rstudio has stopped working. Not sure it is driven by the install but could be. Will keep you posted.






—

Vincent R. Nijs

Associate Professor of Marketing

Rady School of Management

University of California, San Diego

Wells Fargo Hall, 3W116

9500 Gilman Drive # 0553 | La Jolla, CA  920930553

858.822.7459 ǀ vnijs@ucsd.edu

**Comment by mostly-harmless** [comment]
I hadn’t even noticed that brew installed R when it installed littler. I removed the brewed version of R and now Rstudio works again. It seems that using brew for littler may not be a good solution at this point for most mac users. I am installing R and R-gui through brew now and it seems to work with Rstudio as well. That may still be too much work however.



—

Vincent R. Nijs

Associate Professor of Marketing

Rady School of Management

University of California, San Diego

Wells Fargo Hall, 3W116

9500 Gilman Drive # 0553 | La Jolla, CA  920930553

858.822.7459 ǀ vnijs@ucsd.edu

**Comment by mostly-harmless** [comment]
The answer seems to be:





brew tap homebrew/science

brew install littler




If they don’t have brew installed yet they can go here:

http://brew.sh/









—

Vincent R. Nijs

Associate Professor of Marketing

Rady School of Management

University of California, San Diego

Wells Fargo Hall, 3W116

9500 Gilman Drive # 0553 | La Jolla, CA  920930553

858.822.7459 ǀ vnijs@ucsd.edu

**Comment by eddelbuettel** [comment]
Thanks for the update.

**Comment by rkrug** [comment]
I just found the package "littler" - installed it, linked the binary and it is working.
Thanks.
