### ISSUE TITLE
Add install2.r to PATH

### ISSUE THREAD

**Issue by nick-youngblut** [eddelbuettel/littler#110]
For building docker images with R packages via `install2.r` (without using rocker, and potentially multi-stage builds), it would be helpful if `install2.r` was automatically added to the PATH

**Comment by eddelbuettel** [comment]
Sure, but isn't that something you would do in your container?  As I for example do here

https://github.com/rocker-org/rocker/blob/2f92c6c8b8da7b3e61aabc44cacc0439bf267d31/r-base/latest/Dockerfile#L62

It is _not_ something `littler` itself can do as an R package.  No R package adds itself to the $PATH, not even the ones where it would make sense (as `r` from littler, before any of the helpers). 

So unless I am missing something we should close this.

**Comment by nick-youngblut** [comment]
Thanks for pointing out the example!

**Comment by eddelbuettel** [comment]
I live by those examples and use (some of) them each day -- that's why there are so many -- hence I am _in spirit_ fully in favour of your suggestion. But _in practice_ we cannot for an R package.  I do this for `r` for the Debian package of littler though.
