### ISSUE TITLE
[Question]: How to supply Github Personal Access Token with installGithub.r

### ISSUE THREAD

**Issue by tamuanand** [eddelbuettel/littler#113]
Hi @eddelbuettel 

Is it possible to supply a Github PAT (personal access token) when using `installGithub.r`  - especially when using this in a Dockerfile

```
Authenticated requests get a higher rate limit. Check out the documentation for more details.

  To increase your GitHub API rate limit
  - Use `usethis::create_github_token()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.
```

Thanks

**Comment by eddelbuettel** [comment]
I have a PAT in my bash environment (for access-controlled repos, say my students) and it just works for me.

I cannot speak to `usethis` as I do not use it.  If you can reproduce a _minimally_ reproducible complete example I could take a look.

**Comment by eddelbuettel** [comment]
I stand corrected. I define the PAT as `GITHUB_PAT` (as required) via `~/.R/profile.d/*` where I have a simple R snipped looping over all files in that directory and sourcing them; there are IIRC a StackOverflow question or two where I detail that) and `littler` per a very early design decision may not read those files.

But methinks if you define the GITHUB_PAT at the bash level _before R or `r` start_ then it should get in.

**Comment by eddelbuettel** [comment]
You can always do `r -e print(Sys.getenv())` to see what `r` knows / has read.  We an early decision to be faster on startup so we may not read all that R reads.  So here for me:

```sh
$ Rscript -e 'print(Sys.getenv())' | wc -l
143
$ r -e 'print(Sys.getenv())' | wc -l
145
$ 
```

which _oddly_ shows more.  Anyway, that may give you a way to drill down.

**Comment by eddelbuettel** [comment]
As for 'within the context of a Dockerfile' look up documentation about how to pass an environent variable down. From memory that is option `-e ...`.

**Comment by tamuanand** [comment]
Thanks @eddelbuettel 

My specific question: Is there an argument like thing that I can pass to installGithub.r with my GITHUB_PAT

Thanks

**Comment by eddelbuettel** [comment]
We are talking past each other.  `GITHUB_PAT` is an _environment variable_ that gets picked by the appropriate libraries (say: from package `gh`) loaded and launched from `r`.  You do not pass the argument down explicitly: that is the whole point of environment variables which are, in the programming sense, "globals".  Makes sense?

**Comment by tamuanand** [comment]
Hi @eddelbuettel - sure it makes sense. I do not want to have GITHUB_PAT as an env variable as one can look it up from `docker history` etc. I would prefer using ARG in Dockerfile and passing this as an arg to the `installGithub.r` script when doing docker build

**Comment by eddelbuettel** [comment]
Well in that case you have a _specific_ requirement to set an environment variable _from within_ a running session and you will have to work out how to satisfy his.  My first instinct is a tempfile passed down and that is worse if you have snapshotting filesystems.  Anyway: I think this is your deployment question and not an `r` design issue.

**Comment by eddelbuettel** [comment]
I seem to have written most course-asset-access script as `Rscript` files given that my trusted TA was on macOS.  But the general gist remains: an environment variable is a global environment variable.  `r` should get to it.

**Comment by tamuanand** [comment]
Thanks @eddelbuettel

**Comment by eddelbuettel** [comment]
Ah working example I just came across is `installGithub.r` which echo (from the respective library / package given the ability to read from gitbhub) as

```sh
$ installGithub.r someorg/somerepo/some/sub/dir
Using github PAT from envvar GITHUB_PAT
[....]
```
