### ISSUE TITLE
add an 'echo' option?

### ISSUE THREAD

**Issue by bbolker** [eddelbuettel/littler#114]
As noted in [this SO question](https://stackoverflow.com/questions/38312819/r-equivalent-of-bashs-set-x-echo-all-commands-being-executed), one of the ways in which `R CMD BATCH` is usefully different from either `Rscript` or `r` is that it automatically echoes commands.  As pointed out by the answers there, one can either add `options(echo  = TRUE)` in the script, or use the slightly hacky `Rscript -e 'source("myfile.R", echo=TRUE)` approach.  It would be nice (IMO) if `r` offered an "echo source" option (the `-e` flag is taken already; `-x`/`--echo` would mimic `bash` ...

(label this as "wishlist", "low priority")

**Comment by eddelbuettel** [comment]
Are you aware of  `-p` ? Would that do what you want?

**Comment by eddelbuettel** [comment]
Oh you mean as in bash's `set -x`.  Ewww.   :grin:    Really?

**Comment by bbolker** [comment]
The use case here is that we're trying to debug some code being run remotely on an HPC system; we could add print statements everywhere (or `options(echo=TRUE)` to see how far it had gotten at a given time, but it would be convenient if we could toggle this behaviour with a command-line switch ...

**Comment by eddelbuettel** [comment]
Can you actually demonstrate an effect?  I cannot:

```sh
$ r -i -e 'options(echo=TRUE); data(trees, package="datasets"); lm(Girth ~ Height, data=trees)'
$ # ie nothing even with interactive on
$
$ r -i -p -e 'options(echo=TRUE); data(trees, package="datasets"); lm(Girth ~ Height, data=trees)'
$echo
[1] TRUE

[1] "trees"

Call:
lm(formula = Girth ~ Height, data = trees)

Coefficients:
(Intercept)       Height  
     -6.188        0.256  

$ 
$ # -p works as before
$ r -p -e 'data(trees, package="datasets"); lm(Girth ~ Height, data=trees)'
[1] "trees"

Call:
lm(formula = Girth ~ Height, data = trees)

Coefficients:
(Intercept)       Height  
     -6.188        0.256  

$ 
```

**Comment by eddelbuettel** [comment]
Revisiting ...  

```r
> source("/tmp/foo.R")                             # nuttin
> source("/tmp/foo.R", echo=TRUE)       # something

> a <- 2

> b <- a + a
> options(echo=TRUE); source("/tmp/foo.R")   # nuttin again
> 
```

It seems to me that you desire a variant of `source(file)` that has echo on.  I think that is by far done in the easiest way via _an external script_.  Call it `srcecho.r` or what an just call `source()` with `echo=TRUE`.

`littler` has four distinct modes of operating and being called and sourcing a file is just one.  I don't think it makes sense to go all the way to add a new command-line switch _which affects only one of those four modes_.  So I am leaning towards saying "Nope!".   Can you convince me that I am wrong?

**Comment by bbolker** [comment]
Probably not.  This is not a must-have, it would just be nice (IMO).

**Comment by eddelbuettel** [comment]
Sure would be.  Maybe you want to take a look at [inst/examples/](https://github.com/eddelbuettel/littler/tree/master/inst/examples) (which varies from the very simple with one or no arguments to the more complex) and add a file with a nice and easy mnemonic name that tab-completes well?  Some of these scripts I run (at least !!) daily and they have become muscle memory for me.   I was "merely" trying to point out that making a change in `littler.c` was likely not the best venue.   So may a contributed `xource.r` that "sources like `set -x`" ?
