### ISSUE TITLE
r: error while loading shared libraries: libR.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ChillyMomo709** [eddelbuettel/littler#115]
I'm using the docker base image rocker/rstudio-4.3.1.

I've updated the date in `/usr/local/lib/R/etc/Rprofile.site` to 2023-12-19 like so:

```
options(repos = c(CRAN = 'https://packagemanager.posit.co/cran/__linux__/jammy/2023-12-19'), download.file.method = 'libcurl')
# https://docs.rstudio.com/rspm/admin/serving-binaries/#binaries-r-configuration-linux
options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version["platform"], R.version["arch"], R.version["os"])))
```

Updating the littler package goes fine:
```
root@3b13fdd430e5:/# /usr/local/lib/R/site-library/littler/examples/update.r
trying URL 'https://packagemanager.posit.co/cran/__linux__/jammy/2023-12-18/src/contrib/littler_0.3.19.tar.gz'
Content type 'binary/octet-stream' length 102229 bytes (99 KB)
==================================================
downloaded 99 KB

* installing *binary* package ‘littler’ ...
* DONE (littler)

The downloaded source packages are in
        ‘/tmp/downloaded_packages’
```

However when I rerun the update.r script or install any other package:
```
root@3b13fdd430e5:/# /usr/local/lib/R/site-library/littler/examples/update.r
r: error while loading shared libraries: libR.so: cannot open shared object file: No such file or directory
```

Further checking:
```
ldd /usr/local/lib/R/site-library/littler/bin/r
        linux-vdso.so.1 (0x00007ffd3918c000)
        libR.so => not found
        libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007f3508447000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f350868a000)

root@3b13fdd430e5:/# ldd /usr/local/lib/R/bin/exec/R
        linux-vdso.so.1 (0x00007ffc56332000)
        libR.so => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f192014b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f192037e000)
```

But the file libR.so is there but somehow not recognized:
```
root@3b13fdd430e5:/# ll /usr/local/lib/R/lib/libR.so
-rwxr-xr-x 1 root root 13328376 Oct 20 11:51 /usr/local/lib/R/lib/libR.so*
```

Any tips on how to fix this?

**Comment by eddelbuettel** [comment]
That is a 'delicate' usage issue with the versioned.  CCing @eitsupi 

I had that in `r2u` (which uses where it can binaries from p3m) too.  But we *cannot use p3m/ppm/rspm* for `littler` as its build is based on 'their' R binary somewhere in `/opt/R`.  So until we adjust the r-ver container you will have to locally compile `litter` _from source_ so that it picks up the R actually used.  Basically, running `update` (using `r`) risks getting a binary that breaks `r`.

That is at its heart an issue with the usage of these containers, not with `r`.  Also for the snapshot I have here of `rocker/rstudio` it seems to work fine as shipped:

```sh
edd@rob:~$ docker run --rm -ti rocker/rstudio r --version
r ('littler') version 0.3.18

using GNU R Version 4.3.2 (2023-10-31)

Copyright (C) 2006 - 2021  Jeffrey Horner and Dirk Eddelbuettel

r is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License.  For more information about
these matters, see http://www.gnu.org/copyleft/gpl.html.

edd@rob:~$ 
```

**Comment by eddelbuettel** [comment]
Yes. I said so too.  Can you see any way in r-ver to prevent `littler` (the package) from updating?

**Comment by eddelbuettel** [comment]
Anyway, as this is an r-ver usage issue and not a littler issue (in the sense of 'somewhat is wrong with the littler source') but rather an accidental acquisition of a non-working version where it shouldn't I will close this here.

**Comment by eitsupi** [comment]
> Yes. I said so too. Can you see any way in r-ver to prevent `littler` (the package) from updating?

I don't know.

**Comment by eddelbuettel** [comment]
Agreed. I also have not 'obvious' suggestion apart from documenting it.  One (working but kludge-y) way would be to keep littler is a separate .libPaths() entry you prepend.
