### ISSUE TITLE
.Rprofile, .First() or the .libPaths() issue / request

### ISSUE THREAD

**Issue by setempler** [eddelbuettel/littler#13]
The file `.littler.r` is a way to define options for `r`. However, `.Rprofile` files might be already configured and used by users, but it is not regarded by `r`:

    r << EOF
    print(.libPaths())
    EOF
    # [1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"      
    # [3] "/usr/lib/R/library"           
    
    echo 'source("~/.Rprofile"); .First()' > ~/.littler.r
    
    r << EOF                                                 
    print(.libPaths())
    EOF
    # [1] "/home/setempler/.rlib"         "/usr/local/lib/R/site-library"
    # [3] "/usr/lib/R/site-library"       "/usr/lib/R/library"    

It would be nice when `r` sources `.Rprofile` files and runs `.First()` functions, to act more similar to the `R` startup. Also a '--lib' option seems handy, to use like this:

    r - --lib ~/.rlib << EOF
    print(.libPaths())
    EOF

---

Used ubuntu 15.04 R 3.1 littler 0.2.2-1

**Comment by eddelbuettel** [comment]
I looked into this.  Sourcing it at the C code level is a lot of work; it pretty much replicates everything we have in littler so I am unlikely to do it.

The easiest would just be if _you_ sources `~/.Rprofile` from `~/.littler.r`.  Good enough?

**Comment by setempler** [comment]
I will go with sourcing `~/.Rprofile` as in the example I showed.
But looking forward to a `.libPaths()` solution, since this is my major concern.

Thank you for looking into this!

**Comment by eddelbuettel** [comment]
I very much like `.libPaths()` the way it is (and quite strongly believe that if you have a directory you want added all the time, you should do it in `~/.littler/r`) but can see the merit of adding a command-line toggle for it (though the `-l` is already taken).

**Comment by eddelbuettel** [comment]
Please try the current version in the repo; I added support for a `-L | --libpath` option during the morning commute.

**Comment by eddelbuettel** [comment]
@setempler:   It is a little disappointing that you seem to be able to raise an issue here, but appear unable to follow-up when the issue is addressed.

**Comment by setempler** [comment]
@eddelbuettel More patience you must have. I do work in my free time here, which is quite limited due to my phd studies.

Nevertheless I can confirm `-L` functionality and thank you!

    # [08:12:31] set @ air : ~/Source/.github/littler 
    # ./r -e "print(.libPaths())"
    [1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"      
    [3] "/usr/lib/R/library"           
    # [08:12:39] set @ air : ~/Source/.github/littler 
    # ./r -L ~/.libr/air_R-3.1/ -e "print(.libPaths())"
    [1] "/home/set/.libr/air_R-3.1"     "/usr/local/lib/R/site-library"
    [3] "/usr/lib/R/site-library"       "/usr/lib/R/library"

**Comment by eddelbuettel** [comment]
It has been over a week since you posted that "more patience you must have", but I am still essentially speechless by just how rude this was. 
 
I contemplated removing the feature, but then there is no point in lowering oneself to your level.
So the new version still has this feature which you had the audacity to request without willing to test (without being prompted).  Very nice, and I will keep that in mind next time I hear from you, and you request that I spend my time doing (unpaid) work for you.

Sincerely, just another "working entirely in his _free time_ too" open source author.

**Comment by setempler** [comment]
Hi Dirk,

I did not intend to appear rude. Could you please re-read my message with a
focus on the testing I did, and a bit on star wars (therefore also smile,
what is closer to my intention than rudeness - even emotions were not any
intention in the first place).
Please also notice that I could interpret not only your last message as
rude, too!

Still I hope I helped you (and others - I expect a wider user base than us
two) with this, and I can do so in future. For sure I will try to leave
emotions or even emotion inducing statements out of future comments.

I really do appreciate your work!!

Sven

**Comment by eddelbuettel** [comment]
Possible. I am also seeing 

```sh
$ r -L /tmp -p -e'.libPaths()'
[1] "/tmp"                          "/usr/local/lib/R/site-library" "/usr/lib64/R/library"          "/usr/share/R/library"         
$ 
```

On the other hand:


```sh
$ r -L /tmp -p -e'paste(.libPaths(), collapse="|")'
[1] "/tmp|/usr/local/lib/R/site-library|/usr/lib64/R/library|/usr/share/R/library"
$ 
```

Could this be a `print()` or `format()` issue?

**Comment by shabbybanks** [comment]
The question is regarding colon separated values passed to `-L`. So I see:
```bash
$ # this is good (I mean, other than anaconda)
$ r -L "/tmp" -p -e 'paste(.libPaths(),collapse="|")'
[1] "/tmp|/opt/anaconda2/envs/R341/lib/R/library"
$ # this not so much
$ r -L "/tmp:$HOME" -p -e 'paste(.libPaths(),collapse="|")'
[1] "/opt/anaconda2/envs/R341/lib/R/library"
```

**Comment by eddelbuettel** [comment]
Yes, looks like it needs a single item. But because the string is passed through, if R's `.libPaths()` accepts more argument maybe you can sneak them in. This is where it happens:
https://github.com/eddelbuettel/littler/blob/master/src/littler.c#L693-L699
