### ISSUE TITLE
datastdin and header

### ISSUE THREAD

**Issue by hcraT** [eddelbuettel/littler#20]
Hi,
first of all thanks for this very useful program.

The problem is that in my opinion the datastdin should be changed so that it doens't assume the input to have an header. An option to enable the header should be added. This because the current behaviour is in my opinion subtle.

Just to give you an idea the problem affects one example you have on your page because this:
```bash
ls -l /boot | awk '!/^total/ {print $5}' | r -e "fsizes <- readLines(file(\"stdin\")); print(length(fsizes))"
```
is not actually equivalent to this:
```bash
ls -l /boot | awk '!/^total/ {print $5}' | r -de "print(length(X[,1]));"
```
the latter uses the first line as a name for the header of the X table and so the answer is 1 less than the former.

Hope this is clear.

Thank you and best regards,
hcraT

**Comment by eddelbuettel** [comment]
In my opinion data is more trustworthy if it actually _has_ a header --- so I'd rather not encourage the opposite.

As for the conversions: on the command-line you can easily strip or add a header if you need to, so I think I prefer for things to remain as they are.

**Comment by hcraT** [comment]
While working on the command line I tend to assume that input is not provided with a header (because usually it is so). Even you with your example assumed this. So this could be an indication that this is plausible assumption to be made.

Despite I agree on the fact that data is more trustworthy with an header this is not usually what happens on the cli.

Regardless of what you will decide in the end I thank you for your attention!

Best regards,
hcraT.

**Comment by eddelbuettel** [comment]
For the record here is a trivial worked example where just prepending

     echo "foo,bar"

gives you the required header -- indented for clarity, runs on one line

```{.sh}
(echo "foo,bar"; r -e 'write.table(matrix(1:4,2,2), col.names=FALSE, \
                                                  row.names=FALSE, quote=FALSE, sep=",")') \
          |  r -d -e'print(X)'
```
