### ISSUE TITLE
Error: trying to use CRAN without setting a mirror

### ISSUE THREAD

**Issue by kdaily** [eddelbuettel/littler#23]
I'm using `littler (0.2.3-2precise0)` for Ubuntu 12.04, pulled from http://cran.rstudio.com/bin/linux/ubuntu/. After install (and symbolic links to the scripts in `examples`), I'm trying to install a package, but get the following error:

```
ubuntu@ip:~# sudo -Hi
root@ip:~/src# install.r ggplot2
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
```

The bottom of my `/etc/R/Rprofile.site` has the following:

```
options(repos = list(CRAN="http://cran.rstudio.com/"))
```

Am I doing something wrong here? Thanks!

**Comment by kdaily** [comment]
I successfully did this (thanks still to `littler`!):

```
r -e 'install.packages("docopt", repo="http://cran.rstudio.com/")'
install2.r -r http://cran.rstudio.com/ ggplot2
```

**Comment by eddelbuettel** [comment]
I do what you do all the time at work.  Version 0.2.3 now reads `Rprofile.site` (and any local variant).  Do look what it is in your copy of `install.r`.  It should have [this line](https://github.com/eddelbuettel/littler/blob/master/examples/install.r#L21) and pick up repo.  Maybe insert a print there?

[ I too had older `install.r` from previous version in, say, `~/bin/install.r` and then this would fail.  But a new script with the new version should "just work". ]

**Comment by kdaily** [comment]
I've got that line. Added a print as such:

```
repos <- getOption('repos')
message(sprintf("My repos: %s", repos))
```

Still troublesome:

```
root@ip-172-31-14-247:~# install.r docopt
My repos: @CRAN@
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
```

But I figured it I think. From R prompt:

```
> getOption("repos")
$CRAN
[1] "http://cran.rstudio.com/"
```

I'm setting as a named list; could that do it? FYI I took this code from a `rocker` Dockerfile:

https://github.com/rocker-org/rocker/blob/master/r-base/Dockerfile#L41-L53

**Comment by kdaily** [comment]
Which I see now, I'm missing this line:

`echo 'source("/etc/R/Rprofile.site")' >> /etc/littler.r`

**Comment by eddelbuettel** [comment]
That was _the previous_ approach.   Do this:

```{bash}
edd@max:~$ tail -1 /etc/R/Rprofile.site     
cat("Hello world from Rprofile.site\n")
edd@max:~$ r -e'1+1'
Hello world from Rprofile.site
edd@max:~$ 
```

With an explicit `cat()` or `print()` you see more clearly if the file is read, or not.

And I should be running the exact same version as you:

```{bash}
edd@max:~$ r --version
r ('littler') version 0.2.3

git revision 8df31e5 as of Thu Jan 29 17:43:21 2015 -0800
using GNU R Version 3.2.0 (2015-04-16)

Copyright (C) 2006 - 2015  Jeffrey Horner and Dirk Eddelbuettel

r is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License.  For more information about
these matters, see http://www.gnu.org/copyleft/gpl.html.

edd@max:~$ 
```

**Comment by kdaily** [comment]
Just to be clear, you're suggesting doing this *without* adding the sourcing of `/etc/R/Rprofile.site` to `/etc/littler.r`? Or is this still required? Here's what I get:

```
root@ip:~# tail -n 2 /etc/R/Rprofile.site 
options(repos = list(CRAN="http://cran.rstudio.com/"))
cat('Hello world from Rprofile.site\n')
root@ip:~# r -e '1+1'
root@ip:~# install.r ggplot2
My repos: @CRAN@
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
root@ip:~# r --version
r ('littler') version 0.2.3

git revision 8df31e5 as of Thu Jan 29 17:43:21 2015 -0800
using GNU R Version 3.2.0 (2015-04-16)

Copyright (C) 2006 - 2015  Jeffrey Horner and Dirk Eddelbuettel

r is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License.  For more information about
these matters, see http://www.gnu.org/copyleft/gpl.html.
```

**Comment by kdaily** [comment]
Maybe another issue: I'm seeing a different version of `R` when running `r`:

```
root@ip:~# r --version
r ('littler') version 0.2.3

git revision 8df31e5 as of Thu Jan 29 17:43:21 2015 -0800
using GNU R Version 3.2.0 (2015-04-16)
```

```
root@ip:~# R --version
R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.
```

**Comment by eddelbuettel** [comment]
Here is what I suggest:

1. Then write a file Rprofile.site, or add one line to Rprofile.site.

2. Then run a single r expression just as I showed you.

3. That should tell whether Rprofile.site is read (as it should) or not (in case you need to check why).

4. If it is read, add your repo setting code in Rprofile.site.

Ok?

**Comment by kdaily** [comment]
I think that's what I did? Sorry if I'm missing something.

1. Then write a file Rprofile.site, or add one line to Rprofile.site.

```
root@ip:~# tail -n 2 /etc/R/Rprofile.site 
options(repos = list(CRAN="http://cran.rstudio.com/"))
cat('Hello world from Rprofile.site\n')
```

2-3. 

```
root@ip:~# r -e '1+1'
```

No output, so Rprofile.site is not being read from `r`.

From `R` directly, it is being read:

```
root@ip-172-31-5-229:~# R

R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Hello world from Rprofile.site
```

**Comment by eddelbuettel** [comment]
So your version of littler is different from mine.  So I just check ChangeLog -- indeed, I only added reading of `Rprofile` since the last release. Oops.  My apologies.  

So try what you hinted at before:   `echo 'source("/etc/R/Rprofile.site")' > /etc/littler.r`

**Comment by kdaily** [comment]
Ah! Indeed. I pulled directly from Github and it worked as you thought it would. I appreciate the debugging assistance.

**Comment by eddelbuettel** [comment]
I made a real hash of this in the parallel development of [drat](http://dirk.eddelbuettel.com/code/drat.html).  I thought first that `/etc/litter.r` was good and later realized I could just source `Rprofile` directly when `r` starts.  It took a few iteration -- but yes, when this current version gets released we should be there.   Sorry again for sending you down the wrong path at first.

**Comment by ssudan-epidem** [comment]
(as 'lib' is unspecified)
Error in contrib.url(repos, "source") :
  trying to use CRAN without setting a mirror
Calls: install.packages -> contrib.url
Execution halted
this error coming when ever tried to knit. any one could help?

**Comment by eddelbuettel** [comment]
Please don't jump into random five-year old issue tickets of other projects. I plan to delete your post in a few hours.

See eg https://stackoverflow.com/questions/11488174/how-to-select-a-cran-mirror-in-r and my answer therein
https://stackoverflow.com/a/11488727/143305
