### ISSUE TITLE
Execute .First() from .Rprofile

### ISSUE THREAD

**Issue by setempler** [eddelbuettel/littler#24]
Hi Dirk,

I remember that you mentioned that sourcing the `.Rprofile` is quite a task at the C-level.
Therefore **thank you** very much having introduced this very useful feature (201a83a23ad16b5085f9351b50628330ff238687) now!

Is it possible that `littler` also runs the function `.First()` from `.Rprofile` at startup? 

This happens when calling `R|Rscript|R CMD BATCH`, for example, so that
```
r -e 'cat(.libPaths(),"\n")'
/opt/share/software/packages/R-3.2.0/lib64/R/library 
```
acts similar to
```
r -e '.First(); cat(.libPaths(),"\n")'
/home/templer/.local/lib/R/3.2 /opt/share/software/packages/R-3.2.0/lib64/R/library 
```
provided one modifies the library paths within `.First()`.

Best,
Sven.

**Comment by eddelbuettel** [comment]
To me, sourcing `Rprofile.site` site and `~/.Rprofile` is sufficient:  I do not see what adding evaluating `.First()` would get you that you do not already get from the former two.  Am I missing something?

**Comment by eddelbuettel** [comment]
Here is a demo.  You do need the version in git:

```bash
edd@don:~/git/littler(master)$ cat ~/.Rprofile
## Example of .Rprofile
options(width=80, digits=6, digits.secs=6)
## AER page vii
options(prompt="R> ")

local({r <- getOption("repos");
    r["CRAN"] <- "http://cran.rstudio.com"
    r["ghrr"] <- "http://ghrr.github.io/drat"
    r["eddelbuettel"] <- "http://eddelbuettel.github.io/drat"
    options(repos=r)
})

.First <- function() {
    cat("Hello, world from .First()\n")
}

## Example of Rprofile.site
local({
    ## interactive sessions get a fortune cookie
    if (interactive()) {
        require("fortunes", quietly=TRUE,character.only=TRUE)
        print(fortune())
    }
    .First()
})
edd@don:~/git/littler(master)$ ./r -e '2+2'
Hello, world from .First()
edd@don:~/git/littler(master)$ 
```

So once this version is released you get the ability to this.  Right now, you already can with `/etc/littler.r` and `~/.littler.r`.

**Comment by setempler** [comment]
In my example I used the last commit (c9cbae8) to compile and test. `First()` in my `~/.Rprofile` is not called explicitly (neither in /etc/Rprofile.site).

I just was asking if it is feasible to mimic `R` start up as stated in section [10.8](http://cran.r-project.org/doc/manuals/R-intro.html#Customizing-the-environment) of the introduction manual, concerning the functionality of `.First()` [optionally also of `.Last()`], is it?

I see that one could migrate code out of `.First()` or call `.First()` explicitly, as you also showed in the answer.

Thanks.

**Comment by setempler** [comment]
You can close the issue, as sourcing `~/.Rprofile` is quite a help already.

**Comment by eddelbuettel** [comment]
Yes, you have now four hooks for setups as I mentioned. And as I showed you that allows you to define the very `.First()` you want to run, and run it.   As I understand it, this should do -- where else would you get `.First()` from?  

So if it is ok with I'd like to close this.  If you really need more `.First()` support, maybe you could submit a pull request?  

[ Ahh, now you already answered.  So closing this -- new release should get out "soon enough". ]

**Comment by setempler** [comment]
Thanks!

**Comment by setempler** [comment]
It will take some time to get into (integrating the `.First()` call), but I will try on a rainy Sunday... Let you know via pull.

**Comment by eddelbuettel** [comment]
I still don't know why you need it.  When I read `help(Startup)` I get all I need, including the 

```r
local({
   # code here
})
```

to execute setup.  To me, `.First()` is a left-over from old S+ days but maybe I missed something in almost 20 years with S and R :)

**Comment by setempler** [comment]
I am used to set all my environment within `.First()`.
This way I could reload the settings (including a summary print when in
interactive mode) within a session by calling it.
It just seemed easier to type `.First()` vs `source("~/.Rprofile")`.

Did never touch S[+], just had this chapter 10.8 information to get used to
R and it's environment initialization...

**Comment by eddelbuettel** [comment]
1.  Open and editor to edit `~/.Rprofile`
2.  Add a block as follows:
```r
local({
   cat("Hello, world -- from .Rprofile\n")
   if (interactive()) cat("Hello interactive world\n")
   # more code here
})
3. Start R, note the startup messae
4. Run `Rscript -e 'cat(2+2)'`
5. Run `r -p -e '2+2'`
6. Run `r -p -i -e '2+2'`

That should cover use cases.  I think you don't need `.First()`.
