### ISSUE TITLE
Would it be possible to get this added to the yum package manager?

### ISSUE THREAD

**Issue by danielgoldner** [eddelbuettel/littler#25]

**Comment by eddelbuettel** [comment]
You need to talk to the distribution people.  I am a Debian maintainer, so I can look after it in Debian (and hence Ubuntu and other derivatives) but I have no involvement with Fedora, RH, CentOs, ...

**Comment by danielgoldner** [comment]
OK, I'll look into it, but I'm not very familiar with the process.

By the way, thanks for the amazing utility, it has been great for my workflow :)

**Comment by eddelbuettel** [comment]
I use it daily too :)   I have been meaning to rework it so that it becomes a CRAN package, but as it is somewhat non-standard no sure if that will fly at CRAN anyway...
