### ISSUE TITLE
Unable to build release 0.2.3

### ISSUE THREAD

**Issue by severach** [eddelbuettel/littler#29]
https://aur.archlinux.org/packages/littler/

You didn't run bootstrap to make gitversion.h. Bootstrap can't make that file because the release version doesn't come with git info. The release version from Github and your website are both missing the file.
I pulled the necessary values out of the git history and it builds fine. The git version also builds fine.

**Comment by eddelbuettel** [comment]
You may have missed [https://github.com/eddelbuettel/littler/blob/master/INSTALL] which suggests you start from the tar.gz, or if you insist on the repo, run `./bootstrap.sh`.  And if you claim that `bootstrap.sh` fails you need to show some evidence:

```{.bash}
edd@don:~/git/littler(master)$ git pull --all
Fetching origin
Already up-to-date.
edd@don:~/git/littler(master)$ ./bootstrap 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for string.h... (cached) yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking for stdlib.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking for unistd.h... (cached) yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking whether sys/types.h defines makedev... yes
checking for setenv... yes
checking for gettimeofday... yes
checking for time... yes
checking for R... /usr/bin/R
checking if R was built as a shared library... yes
checking for install_name_tool... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
make  all-am
make[1]: Entering directory '/home/edd/git/littler'
gcc -DHAVE_CONFIG_H -I.    -I/usr/share/R/include -O3 -pipe  -MT littler.o -MD -MP -MF .deps/littler.Tpo -c -o littler.o littler.c
mv -f .deps/littler.Tpo .deps/littler.Po
gcc -I/usr/share/R/include -O3 -pipe  littler.o  -Wl,--export-dynamic -fopenmp  -L/usr/lib/R/lib -lR -lpcre -llzma -lbz2 -lz -lrt -ldl -lm -lblas -llapack \
	-Wl,-rpath,/usr/lib/R/lib -Wl,-rpath,/usr/lib/i386-linux-gnu -Wl,-rpath,/usr/lib/jvm/default-java/jre/lib/i386/client   \
	-o r   
make[1]: Leaving directory '/home/edd/git/littler'
edd@don:~/git/littler(master)$ 
```

**Comment by eddelbuettel** [comment]
Or were you saying that the tarball is incomplete?  I think I would have heard.  And the [Debian package](https://packages.debian.org/sid/littler) would not build either.

I think there is probably just a simple misunderstanding here so please state exactly _which_ sources you tried to process _how_ and how this failed.

**Comment by severach** [comment]
0.2.3.tar.gz is incomplete but it's an easy fix so long as you have any other version that compiles nearby.

I can build the git version and 0.2.2.tar.gz as provided. The 0.2.3.tar.gz is missing gitversion.h. For a release you bootstrap on your git repo to produce gitversion.h so it can be included in the release. That allows it to be built without also cloning the git repo. You didn't run bootstrap for 0.2.3.tar.gz so there is no gitversion.h and it can't be built without obtaining gitversion.h by some other means. A git clone by tag would obtain the desired version and bootstrap fine. Any git clone works fine, as you showed.

bootstrap produces gitversion.h but only from a git clone. The .tar.gz versions do not include the git worktree so bootstrap bypasses thinking that gitversion.h should already be present. Having already compiled the git version, I fixed this by looking through the git log and Github for the tag and date to patch into the 0.2.3.tar.gz bootstrap to get it to compile.

I also found it strange there were no complaints. I suspect that experienced packagers see too many easy ways around the problem to bother the author about it.

**Comment by eddelbuettel** [comment]
Where exactly did you take the version from?  Maybe the tarball on my box is (accidentally) incomplete?

"Generally speaking" this works or else I'd get a million bug reports.  Starting from [the standard packages.debian.org page](https://packages.debian.org/sid/littler), I get

```{.shell}
edd@don:/tmp$ rm littler_0.2.3.orig.tar.gz 
edd@don:/tmp$ wget -q http://http.debian.net/debian/pool/main/l/littler/littler_0.2.3.orig.tar.gz
edd@don:/tmp$ tar tvfz littler_0.2.3.orig.tar.gz | grep gitvers
-rw-rw-r-- 1000/1000       471 2015-01-30 01:48 littler-0.2.3/gitversion.h
edd@don:/tmp$ 
```

which has it.  That said, I have been meaning to redo the setup and see if this couldn't be on CRAN as the very related [RInside](https://cran.r-project.org/web/packages/RInside/index.html) package is.

**Comment by severach** [comment]
```
Fixed littler_0.2.3.orig.tar.gz (Debian, and now eddelbuettel.com)
size=143544
md5sums=('5190d3fb0d694f3ed6dbf405cc9a70ac')
sha256sums=('98cd741c68a5c8f65b06c96d2f56d3b44979b3990335e7869b002c005ef80ba7')
```
```
Bad  0.2.3.tar.gz (Github, and formerly eddelbuettel.com)
size=83876
md5sums=('87aeeca21608464e0adf2317f04c2e1d')
sha256sums=('a67abbac4c67b4d8c7dc493f21638da9f7f7ca813811cc36c8c8478b75088655')
```
It's not a partial download.
```
The bad tar contains extra files:
.gitignore   |    168|Mar 14  2015
.travis.yml  |    524|Mar 14  2015

The bad tar lacks files from a fixed complete release: littler_0.2.3.orig.tar.gz (Debian)
aclocal.m4   |  41928|Mar 14  2015
config.h.in  |   2083|Mar 14  2015
configure    | 177871|Mar 14  2015
gitversion.h |    471|Jan 29  2015
Makefile.in  |  29519|Mar 14  2015
```
When I first posted the eddelbuettel.com and Github 0.2.3.tar.gz were both bad. After two identical bad copies I gave up and fixed them from the already working git source. I didn't try the Debian copy.  The eddelbuettel.com file is now fixed to compile. The Github file still does not compile. I downloaded with Firefox from the Github release page to make sure the curl link wasn't bad.

With all this detailed analysis I see a mistake in the above file listing. It's not proper that the date on gitversion.h is 2.5 months earlier than the other files. Open it up and sure enough, the dates inside are right for the file date but wrong for the tar in which it's found.
```
gitversion.h |    471|Jan 29  2015
static const char* gitrevision = "8df31e5";
static const char* gitdate = "Thu Jan 29 17:43:21 2015 -0800";
```
In the git log we find both commits.
```
commit d0313e549407fb4a95084631666ab4c95b0e369b
Author: [xoxoxox]
Date:   Sat Mar 14 08:07:19 2015 -0500

    release 0.2.3

commit 8df31e53e02696fabbc084c7dd27ba148e0c1ba1
Author: [xoxoxox]
Date:   Thu Jan 29 17:43:21 2015 -0800

    release 0.2.2
```
So where does the bad gitversion.h come from? It's from the 0.22 release. This mistake reveals the sequence of events.

The Debian maintainer downloaded the bad 0.2.3.tar.gz missing gitversion.h. When the build crashed they pulled gitversion.h from the previous version and it worked. All that's wrong is a revision that nobody sees. 
```
# r --version
r ('littler') version 0.2.3

git revision 8df31e5 as of Thu Jan 29 17:43:21 2015 -0800
built at 16:34:37 on Sep 14 2015
using GNU R Version 3.2.1 (2015-06-18)
```
The version should look like my version with the right date and commit patched in.
```
r --version
r ('littler') version 0.2.3

git revision d0313e5 as of Sat Mar 14 08:07:19 2015 -0500
built at 16:49:00 on Sep 14 2015
using GNU R Version 3.2.1 (2015-06-18)
```

Upon my notice you corrected the file at eddelbuettel.com from the working but improperly dated Debian copy.

At this time all 0.2.3.tar.gz are bad. The copies at Debian and now eddelbuettel.com compile but with the wrong date stamp. The Github copy won't compile. To fix this you need to

* Fix the Github release 0.2.3.tar.gz

To fix it right you also need to

* Redact the Debian and eddelbuettel.com copies with the proper date and commit.

Or just wait till the next release.

***
While we're in this deep, I'd like to point out two mistakes in bootstrap.
* configure should include "$@" for the configure switches.
* make shouldn't be included in bootstrap. For packaging configure and make are done at a separate times. One solution I've seen is to skip the make if "$@" is non blank.

I sed both away for my build.

**Comment by eddelbuettel** [comment]
> The Debian maintainer downloaded the bad 0.2.3.tar.gz missing gitversion.h. When the build crashed they pulled gitversion.h from the previous version and it worked.

Nope. I am the Debian maintainer.

> Upon my notice you corrected the file at eddelbuettel.com from the working but improperly dated Debian copy.

Nope. I am currently traveling overseas and have more pressing issues than to play games with you. I have **not** replaced a single file. Thanks anyway for assuming I did.

I don't think this is going anywhere. So let's just call it a day.

**Comment by eddelbuettel** [comment]
I later realized that you may have taken the tar.gz from [this auto-generated page](https://github.com/eddelbuettel/littler/releases).  That tarball is autogenerated by github, and does not contain gitversion.h.   That is a case I didn't consider and need to document.     All "my" tarballs are created by a script off the repo and with the creation of the gitversion.h timestamp.
