### ISSUE TITLE
FR for support commandArgs

### ISSUE THREAD

**Issue by jangorecki** [eddelbuettel/littler#32]
While `argv` is somehow clear way it requires the R script to be adjusted to be called from littler. littler could hook the `commandArgs` function and inject own `argv` it would allow running scripts originally written for `Rscript` - more portable.

**Comment by eddelbuettel** [comment]
littler predates Rscript.  I have little interest in this.  Plus, if you use a proper tool like [docopt for R](https://cran.r-project.org/web/packages/docopt/index.html) then it is handled for you.

**Comment by jangorecki** [comment]
Thanks for info. Instead of new dependency the following would `if(!exists("argv")) argv = commandArgs(TRUE)` allows portability of R scripts.

**Comment by eddelbuettel** [comment]
Thanks. I stuck that [onto the wiki](https://github.com/eddelbuettel/littler/wiki/Littler)

**Comment by eddelbuettel** [comment]
I added some comments on the wiki.  The more I think about it, the less sense it makes.

`r` _always_ has `argv` but not `commandArgs(TRUE)`:

```
edd@max:~$ r -e'print(argv); print(commandArgs(TRUE))' a b c
[1] "a" "b" "c"
character(0)
edd@max:~$ 
```

Did you mean to assign the other way?

**Comment by jangorecki** [comment]
I mean a R code which will works the same for both `r` and `Rscript`.

**Comment by eddelbuettel** [comment]
Should the setting of `argv` then be added to `Rscript` instead?

**Comment by jangorecki** [comment]
Yes, but changing `Rscript` behaviour seems to be much harder than adjusting each R script to work for both `r` and `Rscript`.
`argv` seems to be way to go as it is widely adopted outside of R already. Should I fill FR for it somewhere? in bugzilla??

**Comment by eddelbuettel** [comment]
Not sure. You may want to discuss it on r-devel first as you will need a sponsor for the change in any event.
