### ISSUE TITLE
Thoughts on some possible changes to installGithub.r / installRepo.r

### ISSUE THREAD

**Issue by cboettig** [eddelbuettel/littler#45]
- Looks like `installGithub.r` doesn't support the option to pass a CRAN repo (e.g. for installing the dependencies).  This can be handy if I need to install a package from github whose dependencies come from a repo other than CRAN.  Given that this feature is already in `install2.r`, would it be reasonable to add here?  (Might be confusing since `-r` option means something different in `install2.r` vs in `installRepo.r`, not sure what the right course of action is there).  

- I'd like to add an option to set `upgrade_dependencies` argument to `install_github` to FALSE.  While automatically upgrading makes sense sometimes, this logic differs from the default behavior of `install.packages()`, which does not attempt to upgrade all the dependencies on installing a package, and it would be handy to toggle it off.  

Would you consider a PR along these lines?

**Comment by eddelbuettel** [comment]
I don't use either much -- mostly just to rare one-off installs.  Both changes are reasonable.  In more detail:

- You could also rely on your dot files to set repos; I tend to do that system wide ie CRAN, a local one for work, one of my drats is a common set.  That way it avoid the 'yet another option at the command line'.  Come to think about it, we could even dot files / resources for all these littler scripts.  There is now support. (Just thinking out loud.  The immediate fix via docopt works, of course.

- Seems reasonable.  Default same as the current default (which I presume is `TRUE`) ?

**Comment by eddelbuettel** [comment]
Actually, I take the 'dotfiles for littler' idea back.  We once did that, it is a bad idea.  Using `Rprofle{,.site}` or the per-user ones is better.

**Comment by eddelbuettel** [comment]
I think this can be closed.
