### ISSUE TITLE
#question: is it possible to use install2r to fech a tar from the working dir? 

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [eddelbuettel/littler#47]
Hi there, I'm trying to create a customised docker image for my project based on rocker, but  I'm running into trouble with openssl, libssl-dev etc. 

I'm starting with rocker/devel and trying 
`install2.r --error --deps=TRUE \
									-r 'http://cran.rstudio.com' \
									-r 'http://datacube.wu.ac.at' \
									-r 'http://packages.ropensci.org' \
									-r 'http://www.bioconductor.org/packages/release/bioc' \
									
									
									BH \
									DBI \
									NLP \
									R6 \
									Rcpp \
									assertthat \
									chron \
									httpuv \
									lazyeval \
									slam \
									tibble \
									phylobase \
									data.table \
									dplyr \
									jsonlite \
									lubridate \
									plumber \
									stringr \
									tm \
									zoo  `

Can I set my local WORKDIR as an option in -r? Any workarounds? 

Many thanks

**Comment by eddelbuettel** [comment]
I do not understand your question.  The code for install2.r is 84 lines including all comments.  

If you ask whether it can install from tar.gz:  Yes.  That has worked for ages, and for both variants:

```bash
edd@max:~$ install.r /tmp/downloaded_packages/remotes_1.0.0.tar.gz 
* installing *source* package ‘remotes’ ...
** package ‘remotes’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (remotes)
edd@max:~$ install2.r /tmp/downloaded_packages/remotes_1.0.0.tar.gz 
* installing *source* package ‘remotes’ ...
** package ‘remotes’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (remotes)
edd@max:~$ 
```

**Comment by alexDeCastroAtGit** [comment]
Hi DIrk, yes, the question was: 

> Can I use install2r to download from source? 

Thanks for the swift reply. 
Alex
