### ISSUE TITLE
littler install2.r installs package dependencies in default?

### ISSUE THREAD

**Issue by pgensler** [eddelbuettel/littler#52]
Is there an official way to find the "suggested dependencies" of a package from CRAN for a package?
I am trying to build a container with rstan, and it appears that it installs quite a few dependencies, even with no flag set in my install2.r call:
https://github.com/eddelbuettel/littler/blob/master/inst/examples/install2.r

Running this, should show me the dependencies for a given package (please correct me if I am wrong) :
```
> tools::package_dependencies("rstan")
$rstan
[1] "ggplot2"     "StanHeaders" "methods"     "stats4"      "inline"     
[6] "gridExtra"   "Rcpp"        "RcppEigen"   "BH" 
``` 
However, when I install with the following dockerfile, I get quite a few more dependencies than what is listed:

```
FROM rocker/tidyverse:latest
RUN mkdir -p $HOME/.R
COPY R/Makevars /root/.R/Makevars

RUN apt-get update -qq \
    && apt-get -y --no-install-recommends install \
    liblzma-dev \
    libbz2-dev \
    ed \
    clang  \
    ccache \
    default-jdk \
    default-jre \
    && R CMD javareconf \
    && install2.r --error \
        ggstance ggrepel \
        rstan shinystan rstanarm \
        ###My pkgs
        tidytext janitor corrr officer devtools pacman
        tidyquant timetk tibbletime sweep broom prophet \
        forecast prophet lime sparklyr rsparkling \
        formattable httr rvest xml2 jsonlite \
        textclean ggthemes naniar \
    && Rscript -e 'devtools::install_github(c("hadley/multidplyr","jeremystan/tidyjson","ropenscilabs/skimr"))' \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds \
    && rm -rf /var/lib/apt/lists/*
```
which yields this:
```

installing to /usr/local/lib/R/site-library/rstan/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (rstan)

The downloaded source packages are in
	‘/tmp/downloaded_packages’
also installing the dependencies ‘miniUI’, ‘PKI’, ‘RCurl’, ‘RJSONIO’, ‘packrat’, ‘crosstalk’, ‘bayesplot’, ‘colourpicker’, ‘DT’, ‘dygraphs’, ‘gtools’, ‘rsconnect’, ‘shinyjs’, ‘shinythemes’, ‘threejs’, ‘xts’

```

Even this CRAN site for the package(https://cran.r-project.org/web/packages/rstan/index.html) does not list these packages as dependencies, so is there something that I am missing to understand? Does compiling the package make more dependencies, or is it because of my what is in my dockerfile?

The one piece of this that is somewhat concerning is that even some of these other packages will state to install a dependency, but I can't seem to even verify that is needed:
Take Lime
```
installing to /usr/local/lib/R/site-library/lime/libs
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (lime)

The downloaded source packages are in
	‘/tmp/downloaded_packages’
also installing the dependencies ‘config’, ‘rappdirs’
```
Correct me if I'm wrong, but shoulden't once a package is installed, you should be see that it was installed successfully, not simply "the package installed, along with 5 other dependencies".

I guess this triggers a few questions for me:
-if Repo's is null, like in my case, does this attempt to pull the package from CRAN? Not exactly sure on default behaviour in the documentation
- Does compiling the package make more dependencies because of compiling from source, or is it  solely because of my what is in my dockerfile?
-Do we need to be explicit about what CRAN portal to pull from in the ```install2.r``` 
-What is the best practice for checking pkg dependencies when using install2.r?
-Is it possible to easily tell in the docker build file when a package builds successfully with it's dependencies? Or is this avail in a CI build tool to more easily navigate?
 
I have attached my full log for more details. The container does get successfully built with the script if you are wondering. Thanks for your time.

[Terminal Saved Output_DockerfileRun.txt](https://github.com/eddelbuettel/littler/files/1409221/Terminal.Saved.Output_DockerfileRun.txt)

**Comment by eddelbuettel** [comment]
I appreciated your energy level, but I'm sorry that I may not have time for essays this length, and I also never said anywhere I would do generic R counseling here -- try the r-help list or StackOverflow.  

As for your question, did you read the documentation for the _one pertinent function_ here: `install.packages()` ?  You _can_ dial installation of suggests up or down.

**Comment by eddelbuettel** [comment]
Also, I presume you understand that dependencies are in fact a graph, correct?  Ie the (in)famous ten or so tidyverse packages (that are directly listed) expand to a total of around 49 (when I once counted) packages in total.  I would surmise that you have the same here.

**Comment by eddelbuettel** [comment]
Simplest (?) possible answer:

```r
R> library(tools)
R> deps <- package_dependencies("rstan", recursive=TRUE)
R> deps
$rstan
 [1] "ggplot2"      "StanHeaders"  "methods"      "stats4"       "inline"       "gridExtra"   
 [7] "Rcpp"         "RcppEigen"    "BH"           "digest"       "grid"         "gtable"      
[13] "MASS"         "plyr"         "reshape2"     "scales"       "stats"        "tibble"      
[19] "lazyeval"     "grDevices"    "graphics"     "utils"        "Matrix"       "lattice"     
[25] "stringr"      "RColorBrewer" "dichromat"    "munsell"      "labeling"     "R6"          
[31] "viridisLite"  "rlang"        "colorspace"   "stringi"      "magrittr"     "tools"       

R> 
```

**Comment by pgensler** [comment]
The reason I did not post this on SO is because I am asking about the definition of terms about your function, and how dependencies works with regards to install2.r, as when I have tried installing a package from source on my local machine, it does not install all these crazy other pkgs, such as miniUI and RCurl, so I would think that it has something to do with install2.r, as it states:

> "-d --deps DEPS      install suggested dependencies as well [default: NA]"


so one would think that that behavior should override what is happening in install.packages, correct? Does NA mean that this does not install Suggests?
For starters, why is this installing miniUI, RCurl, and packrat with stan, both are not on that list you supplied? I can understand later on in my script, but it just seems it does it at-will.


My main issue that that I can't truly understand the output of building my container, and as I'm going through the build file, nothing seems to line up, which is extremely frustrating.

**Comment by eddelbuettel** [comment]
Again, `install2.r` and particularly `install.r` which I essentially use daily are _trivial and minimal wrappers_ around base R functions.  You seem to suspect that we are doing some magic: it is the opposite.  

It really just calls base R, so if you are confused about its functioning there are better places that this issue ticketing system _provided to improve the `littler` package_.

As for your quoted line:  see `help(install.packages)` as per my last message(s).  It reads:

```
dependencies: logical indicating whether to also install uninstalled
          packages which these packages depend on/link
          to/import/suggest (and so on recursively).  Not used if
          ‘repos = NULL’.  Can also be a character vector, a subset of
          ‘c("Depends", "Imports", "LinkingTo", "Suggests",
          "Enhances")’.

          Only supported if ‘lib’ is of length one (or missing), so it
          is unambiguous where to install the dependent packages.  If
          this is not the case it is ignored, with a warning.

          The default, ‘NA’, means ‘c("Depends", "Imports",
          "LinkingTo")’.

          ‘TRUE’ means to use ‘c("Depends", "Imports", "LinkingTo",
          "Suggests")’ for ‘pkgs’ and ‘c("Depends", "Imports",
          "LinkingTo")’ for added dependencies: this installs all the
          packages needed to run ‘pkgs’, their examples, tests and
          vignettes (if the package author specified them correctly).

          In all of these, ‘"LinkingTo"’ is omitted for binary
          packages.

```

and you want the paragraph in the middle.  Ok?   

I am truly sorry that I can't help you with your container. I am currently tied up with infrastructure issues at my end.   As for your issues, I find that if I simplify, simplify, simplify and simplify some here I eventually get to the issue.

**Comment by pgensler** [comment]
@eddelbuettel I think the core issue here is that if this is truly meant to be a wrapper around ```install.packages```, then at the very least provide a startup message to state "Starting install for package {x}" , and once the install has completed, output a message with "Package Install complete for package {x}".

**Comment by eddelbuettel** [comment]
It is open source software. Exercise your money back guarantee.
