### ISSUE TITLE
littler for non-R people?

### ISSUE THREAD

**Issue by xhudik** [eddelbuettel/littler#54]
Hi, I do  like this package - I think it does a lot what standard R doesn't (or is hidden). I found it yesterday and here are some of my newbie thoughts/ideas:

I understand `littler` as a wrapper for R. That means also people not familiar with R might come to it (while using someones else scripts,..). I suppose, for such people would be beneficial if:

1.  put basic commands (e.g. `install2.r`) into more visible path `/usr/bin` path  - the same as command `r` (question is what commands and how to define path in order to work in all systems)
2. print help if command run without arguments (e.g. `install.r, mph.r` are well done, `install2.r,  r` do not have it). This is especially true for `r` command that is silent if I run it. Printing help would help people who doesnt know the command. Similarly to other standard command like tools  like `awk` - if run without options/parameters print help. 

What do you think?

**Comment by eddelbuettel** [comment]
Well, regarding

1. We generally cannot write there for `R CMD INSTALL ...`.  For things like the Debian package built off, I would need a manual page for each command installed.   Willing to help write all those?

2. Tricky. So far I mostly want `build.r`, `rcc.r`, ... to accept "." as argument.   Auto-help may be pushing it too far.  Also, the Unix Tradition (TM) has 'empty output' on no argument, and help on `-h` or `--help` -- which is what we do. 

But glad you like it. I use it a bazillion times each day too ...

**Comment by xhudik** [comment]
hmm, I went through http://dirk.eddelbuettel.com/code/littler/README and thought also about Rscript. 

Basically, features I wrote about in this issue are in Rscript.  It seems both prograams/packages have their audiences and cases where they fit nicely. It would be strange to bent littler to Rscript or the other way around. Now it makes perfect sense to me and we can close the issue :)

Thanks!
