### ISSUE TITLE
Typo in littler-examples.Rmd front matter?

### ISSUE THREAD

**Issue by kylebmetrum** [eddelbuettel/littler#65]
It seems last update should be 2019. 

`date: "Originally written 2015-10-28; Updated 2017-12-10, 2018-05-24 and 2018-01-06"`

https://github.com/eddelbuettel/littler/blob/master/vignettes/littler-examples.Rmd#L4

**Comment by eddelbuettel** [comment]
Good catch, will fix.  I also noticed (post-release) that the copyright year was off.
