### ISSUE TITLE
More specific guidance on using littler with Mac OS

### ISSUE THREAD

**Issue by davidkane9** [eddelbuettel/littler#66]
I realize that littler may not officially support Mac OS, but I would like to give it a try! I also know that some hints are given in the documentation as to how to use it with Mac OS, but these hints seems to expect a fair amount of systems knowledge.

Could you provide two sentences about how to try littler on the Mac?

My *guess* is that one needs to install it from source while simultaneously passing `configure --program-prefix="l"`. I think that one should be able to do this by using the appropriate incantation on install.packages(), something like:

`install.packages("littler", type = "source", configure.vars = c("--program-prefix='l'"))`

That doesn't work, but I think that something close to that should. Any help much appreciated!

**Comment by eddelbuettel** [comment]
> Could you provide two sentences about how to try littler on the Mac?

I never owned a macOS machine, and don't have access to one.  But I support you all the way if you write some!  It should happen.

The `configure` and install hack is an old.  Feel free to change or propose a change. It may work as `r` too  if you fully qualify the path to it -- I really don't know for lack of access!

**Comment by eddelbuettel** [comment]
Closing for lack of follow-up from OP
