### ISSUE TITLE
Add symlink instructions to startup.

### ISSUE THREAD

**Issue by coatless** [eddelbuettel/littler#68]
From [discussion on r-sig-macos](https://stat.ethz.ch/pipermail/r-sig-mac/2019-March/012925.html), the instructions here are not specific:

> When installing littler using install.packages('littler'), I got below message:
> 
>  * new binary r installed in bin/ subdirectory                                        
>  * consider adding a symbolic link from, e.g., /usr/local/bin                         
>  * on OS X, you may have to name this 'lr' instead 
> 
> How can I create this symbolic link?

Suggestion from @s-u on r-sig-macos was to include:

```R
system(paste("sudo ln -s",shQuote(system.file("bin","r",package="littler")),"/usr/local/bin/lr"))
```

Any objection to modifying the line here: 

https://github.com/eddelbuettel/littler/blob/277700a6d7041250cba63fad33a4fab4e0d4dedf/R/init.R#L15-L19

This could also be shown under the Linux variant as well.

**Comment by eddelbuettel** [comment]
We will not call sudo from package scripts.

**Comment by coatless** [comment]
Whoops, @eddelbuettel the `system()` wrapper should be dropped. The idea is to provide the command to run and not initiate it on behalf of the user.

**Comment by eddelbuettel** [comment]
Not our job to explain the `ln` command to people.
