### ISSUE TITLE
A lot of messages

### ISSUE THREAD

**Issue by acpguedes** [eddelbuettel/littler#70]
This is what happens if I ran any R operations from bash.

```
user@computer:~$ R --vanilla -e 'cat(.3 == .1 + .2)'

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> cat(.3 == .1 + .2)
FALSE> 
```
Same if I do `echo '.3 == .1 + .2' | R`

How do I get only the output of the operation and not the messages of R's commander?

**Comment by eddelbuettel** [comment]
I appear to be confuse between `R` itself -- which is what you run there -- and `r` what this repo is about.

Try actually installing `littler` and accessing its `r` binary (pay attention to the end of the install messages; we cannot to the final recommended softlink to `/usr/local/bin/r` or `~/bin/r` or .. for you).  

I am closing this as it is a non-issue.
