### ISSUE TITLE
Clean-up downloaded files

### ISSUE THREAD

**Issue by csgillespie** [eddelbuettel/littler#73]
In Dockerfiles it's standard to use something like:
```
install2.r XXX \
  && rm -rf  /tmp/downloaded_packages/
```
Could we make this:

 *  an option in install2.r, e.g. -c would run `rm -rf` after install

If you are amiable, then:
 
 * default of TRUE would be nice, but I realise that changes previous behaviour
 * would you like a PR?

**Comment by eddelbuettel** [comment]
i)   Is it standard?
ii)  Even if we said it were, why not clean in another spot?
iii)  I actually _like_ to have the tarballs (for a while) in `/tmp/downloaded_packages/` -- I frequently poke into recent downloads / new packages with emacs.
iv)  That said, we can add a new option to remove-on-demand as you say here.  
v)  I would want the default to be 'as is' _i.e._ "don't remove" but we could listen to an `option()`, say, to make this overrideable.

**Comment by csgillespie** [comment]
i) Is it standard?
> Good question. I do it. I've seen it a couple of other places. Not standard, but you 
probably want to do it in a Dockerfile

ii) Even if we said it were, why not clean in another spot?

> What other spot?

iii) I actually like to have the tarballs (for a while) in /tmp/downloaded_packages/ -- I frequently poke into recent downloads / new packages with emacs.

> OK.

iv) That said, we can add a new option to remove-on-demand as you say here.

> I don't have a strong opinion. I would use it. But ...

v) I would want the default to be 'as is' i.e. "don't remove" but we could listen to an option(), say, to make this overrideable.

> Yep

vi) So sure, a clean PR along those lines would work.

> OK. I'll have a stab next week

**Comment by eddelbuettel** [comment]
Re "what other spot":  some of the Rocker Dockerfiles have plain old `rm -f` calls i  them for this.

**Comment by csgillespie** [comment]
After thinking about this, I'm not sure if this is the correct thing. I suspect I've been in docker world a bit too long. 

Closing. If you think it is a good idea, then happy to submit a PR.
