### ISSUE TITLE
Exit status for example scripts

### ISSUE THREAD

**Issue by mllg** [eddelbuettel/littler#74]
Most example scripts do not behave like good unix citizens; they always exit with status 0:

```bash
$ install.r "foo"; echo $?
Warning message:
package ‘foo’ is not available (for R version 3.6.1)
0
```

Same for `rcc.r` where I expected `$? > 0` for a failing check.

**Comment by eddelbuettel** [comment]
Interesting.  I never quite them in pipelines, but used them _a frigging lot_ on the command-line.

We may want to review `install.r`, `install2.r`, `rcc.r`, `render.r`, ... for this.

**Comment by eddelbuettel** [comment]
I have some very vague memory of looking into this a loooong time ago.  It all works if you set `q(status=X)`:

```sh
edd@rob:/tmp$ cat foo.r 
#!/usr/bin/r

q(status=2)
edd@rob:/tmp$ ./foo.r; echo $?
2
edd@rob:/tmp$ 
```

Which ones did you have in mind?  `install*.r` and `rcc.r` ?  The latter one is particularly tricky because how do we map ERROR, WARNING and NOTE to a return code?

**Comment by mllg** [comment]
> Which ones did you have in mind? `install*.r` and `rcc.r` ?

Yes, these two.



> The latter one is particularly tricky because how do we map ERROR, WARNING and NOTE to a return code?

Yep, that's not easy. Introduce new command line args? `--warnings-are-errors` and `--notes-are-errors`?

@gaborcsardi how is `rcmdcheck::rcmdcheck()$status` defined? I couldn't find it in the docs.

**Comment by gaborcsardi** [comment]
I believe it is the exit code of the `R CMD check` process. Maybe you want to expose the `error_on` argument?
```
#' @param error_on Whether to throw an error on `R CMD check` failures.
#'   Note that the check is always completed (unless a timeout happens),
#'   and the error is only thrown after completion. If `"never"`, then
#'   no errors are thrown. If `"error"`, then only `ERROR` failures
#'   generate errors. If `"warning"`, then `WARNING` failures generate
#'   errors as well. If `"note"`, then any check failure generated an
#'   error.
```

**Comment by eddelbuettel** [comment]
Yes, happy to extend `rcc.r` with additional switched -- it is so cheap and easy to do thanks to [doctopt](https://cran.r-project.org/package=docopt).  I have a final `sapply` in there -- we may need a 'reduce' step from that.  Do you want to play around and suggest a simple PR?

**Comment by eddelbuettel** [comment]
I just pushed a first pass in 6819b151093ca18efb35c455944f2aa76542f383; you can probably fetch the [raw file rcc.r](https://raw.githubusercontent.com/eddelbuettel/littler/master/inst/examples/rcc.r)  to play with locally.

**Comment by mllg** [comment]
> I just pushed a first pass in [6819b15](https://github.com/eddelbuettel/littler/commit/6819b151093ca18efb35c455944f2aa76542f383); you can probably fetch the [raw file rcc.r](https://raw.githubusercontent.com/eddelbuettel/littler/master/inst/examples/rcc.r) to play with locally.

Works perfectly. 

Only the reduce step is missing. Something like this?
```r
status <- max(sapply(rc, `[[`, "status"))
q(status=status)
```

OTOH, I wonder if `rcc.r` really needs to be vectorized. The return value would be well-defined if only one path could be provided.

**Comment by eddelbuettel** [comment]
Yes, I was thinking about those two issues too.   The `max` reducer is probably the way to go, same `install.r` and `install2.r`.   One could argue in favour of doing away with the `sapply` but then again it is the current interface, and I used it once or twice that way...

**Comment by eddelbuettel** [comment]
Done in 6f0f9f75436acd4cc1ad1498d7d5a4baf23057f3 so I think this can be closed too.
