### ISSUE TITLE
update.r / libloc

### ISSUE THREAD

**Issue by mllg** [eddelbuettel/littler#75]
> -l --libloc LIBLOC  location in which to install [default: /usr/local/lib/R/site-library]

1. The description is wrong, `libloc` is passed to `update.packages()` as `lib.loc` and determines which libraries to search through for packages to update. What is described here is the `instlib` argument of `update.packages()`.
2. The default is not good. It should default to `NULL` (which translates to all libraries in `.libPaths()`).

**Comment by eddelbuettel** [comment]
It's messy. Historically, `install.r` did nothing and just installed in the first element of `.libPaths()`. For all my Debian systems that was `/usr/local/lib/R/site-library` (and never below `~`).   

Then the need to set a target arose, and we covered it in `install2.r` which actually takes options.  

Now, I happen to have a messier situation at work where I need 1.) above -- use `LIBLOC` as a target.  But come to think about 2,) is actually good too -- I was wondering about using `.libPaths()[1]` (which is the target) but a full dependency resolution as you suggest via `NULL` is probably better.  Will mull it over on the morning run now :)

**Comment by eddelbuettel** [comment]
Have a look at 6f0f9f75436acd4cc1ad1498d7d5a4baf23057f3 -- it should address, or at least improve things.
