### ISSUE TITLE
installation error:  /usr/bin/ld: cannot find -llzma

### ISSUE THREAD

**Issue by tlyim** [eddelbuettel/littler#76]
Tried to install `littler` locally on a linux cluster without root access and got the following issue. Do you see any simple quick fix? (I'm a novice user of linux, C, compliation, etc)

```
littler.c: In function ‘littler_InitTempDir’:
littler.c:352:5: warning: implicit declaration of function ‘setenv’ [-Wimplicit-function-declaration]
     if (setenv("R_SESSION_TMPDIR",tmp,1) != 0){
     ^
littler.c: In function ‘main’:
littler.c:708:13: warning: implicit declaration of function ‘strtok_r’ [-Wimplicit-function-declaration]
             token = strtok_r(ptr, ",", &strptr);
             ^
littler.c:708:19: warning: assignment makes pointer from integer without a cast
             token = strtok_r(ptr, ",", &strptr);
                   ^
/usr/bin/ld: cannot find -llzma
/usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
make: *** [r] Error 1
ERROR: compilation failed for package ‘littler’
```

Found something on SO like [this one](https://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary) but couldn't figure out how to apply it in this context here.

Session info:
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.7 (Maipo)

Matrix products: default
BLAS: /usr/local/sas/grid/R-3.5.1-linux/lib64/R/lib/libRblas.so
LAPACK: /usr/local/sas/grid/R-3.5.1-linux/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] methods base

loaded via a namespace (and not attached):
[1] utils_3.5.1

[1] "/home/city/sbbg070/R_library/3.5"
[2] "/usr/local/sas/grid/R-3.5.1-linux-library"
[3] "/usr/local/sas/grid/R-3.5.1-linux/lib64/R/library"

gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
```

**Comment by eddelbuettel** [comment]
I suspect you installed R as a rpm binary.  In that case, R is configured and built a certain way that is recorded.  If you do `R CMD config --ldflags` in the shell, I suspect you will also see `-llzma -lbz2` on that line.  E.g. on Ubuntu I have (with an edited line-break, it is just one line in the shell)

    edd@rob:~$ R CMD config --ldflags
    -Wl,--export-dynamic -fopenmp -Wl,-Bsymbolic-functions -Wl,-z,relro -L/usr/lib/R/lib \
           -lR -lpcre2-8 -lpcre -llzma -lbz2 -lz -lrt -ldl -lm -licuuc -licui18n
    edd@rob:~$ 

This means _R_ needs the libraries, not littler per se.  So you need to find them for RHEL.  They may be called `lzma-devel` and `bz2-devel` or maybe `liblzma-devel` and `libbz2-devel`.  Install those, and try again.  The error will be gone, you may see a new one :-) or it may just work.  As it should on a more development-friendly system than RHEL.

**Comment by eddelbuettel** [comment]
Did you get that working?  Can we close this?  Or would you need other help?

**Comment by eddelbuettel** [comment]
Quick googling reveals you probably want

    yum install xz-devel bzip2-libs-devel

**Comment by tlyim** [comment]
Thanks for the explanation and suggestions. Cannot use yum without root access. Will try to get the cluster admin to install the required libraries. Thanks.

**Comment by tlyim** [comment]
In case others also do not have root access but need to install the missing libraries on a linux cluster, below is how I did the installations locally:

`wget https://tukaani.org/xz/xz-5.3.1alpha.tar.xz`
`tar xf xz-5.3.1alpha.tar.xz`

(see details https://askubuntu.com/questions/92328/how-do-i-uncompress-a-tarball-that-uses-xz)

`cd xz-5.3.1alpha`

then follow the installation notes at http://docs.hpc.shef.ac.uk/en/latest/iceberg/software/apps/xzutils.html

Similarly, download https://downloads.sourceforge.net/project/bzip2/bzip2-1.0.6.tar.gz ;
then follow the installation notes at https://docs.hpc.shef.ac.uk/en/latest/iceberg/software/libs/bzip2.html#bzip2
