### ISSUE TITLE
littler and R difference on system()

### ISSUE THREAD

**Issue by olesendan** [eddelbuettel/littler#77]
Hi.

I've stumbled across a scenario, which I don't understand. I probally doing something wrong, but can't quite see it.

My setup is:
archlinux
i3wm
bash
urxvt
R
radian

I'm trying to do the following. having a R function, wich I can call from R or in a bash script through littler

My function is

```
do_open_term <- function() {  
system("urxvt", wait=FALSE)  
}      
```

my script is 
do_open_term.rs:
```
#!/usr/local/bin/r -tqp  
doutilitiesr::do_open_term()  
``` 

in R I can open a new terminal window, with do_open_term(), in the current folder. This terminal seems to work as expected.

When I run my script, do_open_term.rs, from the commandline I seem to get at different environment, which is apparent when I run radian.

I will try to explain the different behaviour.

if I run radian from a normal terminal window, I get radian as expected(with loaded R packages, and loaded Rprofile and radian_profile)

if I start a terminal with my script, and then runs radian. radian starts, but without reading Rprofile, like It don't see Rprofile. 
If I run R in this terminal, It also don't run Rprofile. But It has my libpaths.

I would expect littler to start a terminal through system() in the same state as R. Is my understanding wrong?

Can you point me in a direction?

Greetings from Denmark
Dan Olesen

**Comment by eddelbuettel** [comment]
I am not entirely sure I understand your workflow.  

I do know that littler's `r` "used to" not read any dotfiles (for speed) but we changed that.  Did you read what we wrote in the [littler FAQ](https://cloud.r-project.org/web/packages/littler/vignettes/littler-faq.html#no_renviron) about it?

**Comment by olesendan** [comment]
Hi.

After my first comment, I've added readRenviron to .littler.r, so now I have my libpaths.

regarding my workflow, I'v tried to explain it better in my first comment.

**Comment by eddelbuettel** [comment]
> no I have my `.libPaths()` 

Good. So do I.  I have been running a bazillion cron jobs faithfully with littler in the decade and a half it existed.  I tend write _some_ system-wide settings in R's `etc/R*site` files.  And `r` generally sees those.

> But It still seems to open a terminal in a different state.

You would need to be more explicit if you want me to help you.  (And loading terminals is a whole different ballgame as some are what is called 'login' terminal, some are not, ...  Maddening.  For `bash` I now mostly enfore `.bashrc` and `.bash_profile` and `.profile` and ... for consistency.  But you may be "the first" to venture into launching  terminal so if something "is different" you may need to dig locally.  I will try to help.)

**Comment by olesendan** [comment]
Hi.

Thanks for your replies.

I have tried different ways to test what happens. every time I start in a terminal window.
1. scenario:
start R
run do_open_term() -> a terminal window opens. 
In the new terminal window I start radian or R. Both programs starts. R loads .Renviron and .Rprofile, radian loads .Rprofile, .Renviron and .radian_profile.

2. scenario
start radian
run do_open_term() -> a terminal window opens. 
In the new terminal window I start radian or R. Both programs starts. R loads .Renviron and .Rprofile, radian loads .Rprofile, .Renviron and .radian_profile.

3. scenario
from terminal run script do_open_term.rs -> a terminal window opens. 
if I run R or radian in the original terminal, they start as expected.
If I start radian or R in the new terminal. Both programs starts, but they do not load as expected. R don't load .Renviron, and .Rprofile, radian don't load .Rprofile, .Renviron and .radian_profile.

4. scenario
from terminal run r -e 'system("urxvt", wait=FALSE)' -> a terminal window opens. 
if I run R or radian in the original terminal, they start as expected.
If I start radian or R in the new terminal. Both programs starts, but they do not load as expected. R don't load .Renviron, and .Rprofile, radian don't load .Rprofile, .Renviron and .radian_profile.

Am I wrong if I expect littler to open a terminal window with system("urxvt", wait=FALSE), in the same state as R?

greetings from denmark
Dan Olesen

**Comment by olesendan** [comment]
Hi

I have two bash confic files.

bachrc
```
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# PS1='[\u@\h \W]\$ '
PS1="\n\[\u@\h \w\]:\n\$(/bin/ls -1 | /usr/bin/wc -l | /bin/sed 's: ::g') files, \$(/bin/ls -lah | /bin/grep -m 1 total | /bin/sed 's/total //')b\$ "

if [ -f ~/.config/git/git-prompt.sh ]; then
. ~/.config/git/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=1
export PS1="\n\[\u@\h \w\]:\n\$(/bin/ls -1 | /usr/bin/wc -l | /bin/sed 's: ::g') files, \$(/bin/ls -lah | /bin/grep -m 1 total | /bin/sed 's/total //')b\$(__git_ps1 ' (%s)')\$ "
fi

PS2=" > "

if [ -f /etc/bash_completion ]; then 
    . /etc/bash_completion
fi

if [ -f ~/.config/git/git-completion.bash ]; then
    . ~/.config/git/git-completion.bash
fi

if [ -f ~/data/references/main.bib ]; then
    export bibtex="$HOME/data/references/main.bib"
fi

# -- fzf finder setup {{{2
source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash

# default for fzf_bibtex
export FZF_BIBTEX_CACHEDIR="/data/dano/docs/tmp/fzf_bibtex/"
export FZF_BIBTEX_SOURCES="/data/dano/docs/bibliotek/references/main.bib:/data/dano/docs/bibliotek/references/zotero-lib.bib" # path to bibtex file; multiple items separated by a ':'


# --- settings {{{3

export FZF_DEFAULT_OPTS="--ansi --preview '(highlight -O ansi -l {} 2> /dev/null ||
cat {} || tree -C {}) 2> /dev/null | head -200'"
complete -o bashdefault -o default -F _fzf_path_completion zathura
#  }}}

# }}}

# alias --{{{2

alias ls='ls -vF --color=auto --group-directories-first'
alias R='R --no-save --no-restore-data --interactive'
alias vim='nvim'
alias cddata='cd $HOME/data/'
alias cdproj='cd $HOME/data/projects/'
alias cdh='cd $HOME'
alias cd~='cd $HOME'
alias cd.='cd .'
alias cd..='cd ..'
alias cdpics='cd $HOME/data/pictures/'
alias ebc='vim $HOME/.bashrc'
alias evc='vim $HOME/.config/nvim/init.vim'
alias ei3c='vim $HOME/.config/i3/config'
# alias rm
alias rm='echo "rm er disabled, brug delete el. remove(rm) istedet"'
alias remove='/bin/rm -irv'
alias delete='do_delete.rs'
alias dup='do_open_term.rs'

alias git_status='do_git_status.rs'
# }}}
```
bash_profile

```
#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc
export EDITOR="nvim"
export TERMINAL="urxvt"
export BROWSER="qutebrowser"
export XTERM="urxvt"
export TERM="urxvt" #xterm


if [[ -z $(echo $PATH | grep -o $HOME/bin) ]]
then
    export PATH="${PATH}:$HOME/bin"
fi

if [[ -z $(echo $PATH | grep -o $HOME/go/bin) ]]
then
    export PATH="${PATH}:$HOME/go/bin"
fi

if [[ "$(tty)" = "/dev/tty1" ]]; then
	pgrep i3 || startx
fi
```
Dan

**Comment by eddelbuettel** [comment]
The more I look at this the more I think your expectations are wrong.

R and Radian are "UIs".  They have the REPL.  They wait for user input.

r does not, and _by design_.  That is a little like folks who launched GUI frontends (tcltk 15 years ago, then RGtk, now everybody does shiny).  You may need a controlling tty behind it -- the old 'hit enter to continue' or alike.

But I see no shortcomings in documented or expected littler behaviour so I am leaning towards closing this.  Methinks you want something like a button on your desktop to spawn a new R shell. Maybe littler is not the best launcher for that?

**Comment by olesendan** [comment]
I'm just a nembie, trying to learn.
the purpose whit this little function in R, was to learn general programming through R. I wanted to see, if if could just use R for alle my workflows.

I'm just having problems getting my head around why R and r treats a function differently. I've not been here for long, so do not know how things were 15 years ago.

regarding your comment about UI's. Is littler and R CMD then run outside the graphical environment, and the settings from that environment is not set?

If you say the behaviour is expected, then I will not go futher down this road.

I'm on the commandline, so can't have a button. I have an alias, to launch a terminal in the same folder. I wanted to see, if I could create the functionality in R

Greetings from denmark
Dan

**Comment by eddelbuettel** [comment]
Sure.  `r` is like a shell script here.  When it is done, control returns.  So an xterm is opened, nothing happens, and it closes.  That is how that is supposed to work.   

Have you look into something `tmux` (or as I like, `byobu` as a nice frontend) for multiple persistent sessions?

**Comment by olesendan** [comment]
Thanks for your patience.

I will look in to byobu.

I'm closing this issue

Dan
