### ISSUE TITLE
a note about using littler inside zsh shell

### ISSUE THREAD

**Issue by aborruso** [eddelbuettel/littler#79]
Hi,
if I run the first example in zsh shell `echo 'cat(pi^2,"\n")' | r` I have `littler: Incomplete Line! Need more code! (2)`.

If I run `echo 'cat(pi^2)' | r`, it's ok.

Could it be useful to add some related notes in the documentation?

Thank you

**Comment by eddelbuettel** [comment]
Sure. I can at least add a few words as in 

>  (and `zsh`  users can omit the newline)

or some such.

**Comment by aborruso** [comment]
thank you

**Comment by eddelbuettel** [comment]
Why are you opening and closing tickets?  This isn't meant like an email system. 

If you just want to comment, maybe use StackOverflow?

Both were valid points (if only on debugging) and _when you close them I may forget about them_.  

Can you please reopen both?

**Comment by aborruso** [comment]
I have opened the issues here because it seems to me that this is a great project, and I thought it would be useful to add my notes.

Thank you

**Comment by eddelbuettel** [comment]
I just looked into that, and I think you were not correct.  (And I think that issue was raised years ago already, but I don't know it was here or at the previous repo.)   In short, `r` is something else for zsh.

And what you suggested that does not work.  

Here is a snippet from a Docker container with R and littler to which I added zsh:

```sh
0087b9a52c11# echo 'cat(pi^2, "\\n")'   # just echo
cat(pi^2, "\n") # just echo
0087b9a52c11# echo 'cat(pi^2, "\\n")' | /usr/bin/r  
9.869604 
0087b9a52c11#
```

whereas (and that is the tricky bit) just using 'r' does not work:

```sh
0087b9a52c11# echo 'cat(pi^2, "\\n")' | r
echo 'cat(pi^2, "\\n")'
cat(pi^2, "\n")
0087b9a52c11# 
```

It just echos output.  Not what we want.  

There is an old entry in the ChangeLog from 2006 (!!) that we had once documented `r` as clashing with the `zsh` builtin.

**Comment by aborruso** [comment]
Hi @eddelbuettel , not for me, the one below is my shell.

As you can see `r` is your `r`, and I'm using debian

![image](https://user-images.githubusercontent.com/30607/84862993-742ca800-b074-11ea-8294-54d8dff0b290.png)

**Comment by eddelbuettel** [comment]
_Please_ do not post _pictures_ of code.  Post code.  Nobody can copy and post from code. 

So you are doing something different from what I do.  So be it.  I wrote the example for `bash` and it works.  Good enough.

**Comment by aborruso** [comment]
@eddelbuettel sorry for the image.

Below my shell and my commands. I run `echo 'cat(pi+2)'`.

If I run `echo 'cat(pi+2, "\n")' | r`  I have `littler: Incomplete Line! Need more code! (2)`.

I'm not using docker.

```
➜  trash echo 'cat(pi+2)' | r
5.141593%                                                                                                               ➜  trash cat /etc/debian_version
bullseye/sid
➜  trash which r
r: aliased to /usr/bin/r
➜  trash r -h

Usage: r [options] [-|file]

Launch GNU R to execute the R commands supplied in the specified file, or
from stdin if '-' is used. Suitable for so-called shebang '#!/'-line scripts.

Options:
  -h, --help           Give this help list
      --usage          Give a short usage message
  -V, --version        Show the version number
  -v, --vanilla        Pass the '--vanilla' option to R
  -t, --rtemp          Use per-session temporary directory as R does
  -i, --interactive    Let interactive() return 'true' rather than 'false'
  -q, --quick          Skip autoload / delayed assign of default libraries
  -p, --verbose        Print the value of expressions to the console
  -l, --packages list  Load the R packages from the comma-separated 'list'
  -d, --datastdin      Prepend command to load 'X' as csv from stdin
  -L, --libpath dir    Add directory to library path via '.libPaths(dir)'
  -e, --eval expr      Let R evaluate 'expr'


➜  trash echo $ZSH_VERSION
5.8
```

**Comment by eddelbuettel** [comment]
And maybe you redefined another alias.  Here is `zsh` _again_ freshly added in Docker. Note the `which r`.

```sh
root@61e803f7b6d2:/tmp# apt install -y zsh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  zsh-common
Suggested packages:
  zsh-doc
The following NEW packages will be installed:
  zsh zsh-common
0 upgraded, 2 newly installed, 0 to remove and 72 not upgraded.
Need to get 4,838 kB of archives.
After this operation, 18.3 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian testing/main amd64 zsh-common all 5.8-4 [3,937 kB]
Get:2 http://deb.debian.org/debian testing/main amd64 zsh amd64 5.8-4 [901 kB]
Fetched 4,838 kB in 1s (3,644 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package zsh-common.
(Reading database ... 17927 files and directories currently installed.)
Preparing to unpack .../zsh-common_5.8-4_all.deb ...
Unpacking zsh-common (5.8-4) ...
Selecting previously unselected package zsh.
Preparing to unpack .../archives/zsh_5.8-4_amd64.deb ...
Unpacking zsh (5.8-4) ...
Setting up zsh-common (5.8-4) ...
Setting up zsh (5.8-4) ...
root@61e803f7b6d2:/tmp# zsh
61e803f7b6d2# which r
r: shell built-in command
61e803f7b6d2# 
```

And if I then alias `/usr/bin/r` to something else, say `lr` it works with an without an added newline, but differs by adding a newline:

```sh
61e803f7b6d2# alias lr=/usr/bin/r
61e803f7b6d2# echo 'cat(pi^2)' | lr
9.869604#                                                                                                                                                                                                          61e803f7b6d2# echo 'cat(pi^2, "\\n")' | lr 
9.869604 
61e803f7b6d2# 
```

**Comment by eddelbuettel** [comment]
Use two backslashes to protect the initial backslash which `zsh` takes literally.

**Comment by aborruso** [comment]
I want to emphasize that I did all this, because littler is a great product and because zsh is widely used.

Thank you @eddelbuettel , if I bothered you. I'm sorry and I apologize
