### ISSUE TITLE
A question and possibly feature request

### ISSUE THREAD

**Issue by rkrug** [eddelbuettel/littler#84]
Hi

I am using littler to script automated pipeline processing using docker on an open stack vm on which linux is running. My main computer is a Mac. Now I have the problem, that the shebang in linux and Mac needs to be different.

I know that you like `r` and I did as well. But wouldn't it be possible to include an alias, e.g. `lr` which one could use on all OS?

I can do it manually, but would prefer (because of compatibility and reproducibility) an out-of-the-box solution.

Thanks,

Rainer

**Comment by eddelbuettel** [comment]
I suspect you can do that locally in your patch.  But as the language is called R this interpreter is `r`.  

So I am truly sorry, but I am not intending on making a global change (after a decade-plus of existing behavior) because of some sillyness in one operating system I don't use.

**Comment by rkrug** [comment]
As I said - not a change, but an addition.

Thanks for answering anyway.
