### ISSUE TITLE
dylib error with littler

### ISSUE THREAD

**Issue by barryzee** [eddelbuettel/littler#85]
I am trying to use littler to pipe the output of a gawk script into an r program . I am using the terminal program in the latest build of mac OS.

I installed by downloading and unzipping the mac binary. the unzipped package ended up in my Downloads folder. I tried running it from that location, using the full path name in the command line containing the pipe (if you can suggest the proper location for me to move this package to, I would appreciate it).

I got an error message (shown below, after the command line). I would appreciate any help as to how to resolve this.

Barrys-Mac-mini:home barryzeeberg$ sudo tcpflow -c host 045.077.078.199 | gawk -f /Users/barryzeeberg/Desktop/hearts/tcpflow/new_code/in_line_versions/gawk_programs/both.inline.awk | /Users/barryzeeberg/Downloads/littler/bin/r  /Users/barryzeeberg/Desktop/hearts/tcpflow/new_code/in_line_versions/R_code/sfile.inline.R
  /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
  Referenced from: /Users/barryzeeberg/Downloads/littler/bin/r
  Reason: image not found
reportfilename: ./report.xml
./report.xml: Operation not supported
Abort trap: 6

**Comment by eddelbuettel** [comment]
I am not a macOS user so this limits a little what I can say but in short this should work:

```sh
$ r -e 'print(2+2)'
[1] 4
$ 
```

I presume you have a prebuilt version of `r`. I might be a good idea to inquire with whoever built it.

**Comment by eddelbuettel** [comment]
Closing this issue as it is inactive.  If you think the issue is still pertinent please reopen, ideally with additional reproducible examplesl. Thanks
