### ISSUE TITLE
installGithub.r cache files?

### ISSUE THREAD

**Issue by eitsupi** [eddelbuettel/littler#87]
When using `installGithub.r` in rocker containers, I noticed that multiple files were created in the `/tmp` directory.
This is not reproduced by `Rscript -e "remotes::install_github()"`.

On r-base.

```shell
$ docker run --rm -it r-base bash
```

When use `Rscript -e "remotes::install_github()"`:

```shell
root@47823eee5ec5:/# install2.r remotes
trying URL 'https://cloud.r-project.org/src/contrib/remotes_2.4.0.tar.gz'
Content type 'application/x-gzip' length 149836 bytes (146 KB)
==================================================
downloaded 146 KB

* installing *source* package ‘remotes’ ...
** package ‘remotes’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (remotes)

The downloaded source packages are in
        ‘/tmp/downloaded_packages’
root@47823eee5ec5:/# ls /tmp
downloaded_packages
root@47823eee5ec5:/# Rscript -e "remotes::install_github('eddelbuettel/drat')"
Downloading GitHub repo eddelbuettel/drat@HEAD
Running `R CMD build`...
* checking for file ‘/tmp/RtmpAlA2MX/remotes9c13132f72/eddelbuettel-drat-9b2cad6/DESCRIPTION’ ... OK
* preparing ‘drat’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘drat_0.2.1.tar.gz’
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘drat’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (drat)
root@47823eee5ec5:/# ls /tmp
downloaded_packages
```

When use `installGithub.r`:

```shell
root@4e09517160b7:/# install2.r remotes
trying URL 'https://cloud.r-project.org/src/contrib/remotes_2.4.0.tar.gz'
Content type 'application/x-gzip' length 149836 bytes (146 KB)
==================================================
downloaded 146 KB

* installing *source* package ‘remotes’ ...
** package ‘remotes’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (remotes)

The downloaded source packages are in
        ‘/tmp/downloaded_packages’
root@4e09517160b7:/# ls /tmp
downloaded_packages
root@4e09517160b7:/# installGithub.r eddelbuettel/drat
Downloading GitHub repo eddelbuettel/drat@HEAD
Running `R CMD build`...
* checking for file ‘/tmp/remotes9c2944759f/eddelbuettel-drat-9b2cad6/DESCRIPTION’ ... OK
* preparing ‘drat’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘drat_0.2.1.tar.gz’
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘drat’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (drat)
root@4e09517160b7:/# ls /tmp
downloaded_packages              libloc_180_a38f7d5813344af9.rds
file9c3de1eb8b                   remotes9c2944759f
libloc_169_8f48fc7d1db1bb3e.rds  repos_https%3A%2F%2Fcloud.r-project.org%2Fsrc%2Fcontrib.rds
libloc_174_173b0d0583319ed2.rds
```

I am having trouble deleting the files because they are not grouped in a single directory like `/tmp/downloads_packages`.
Can you give me any ideas?

**Comment by eddelbuettel** [comment]
Turn on the interactive flag, i.e. `r -i ...name of your script`, or don't run `installGithub.r` directly. 

It is due to an (old) design choice inside littler about what to do with temporaries directory. I happen to _like_ the fact that when I run `install.r` or `update.r` the downloads remain `/tmp/downloaded_packages/` (as opposed to vanish from a per-session temp directory that, after the short life of that scripts, is gone.  

We could possibly turn on `-i` for this scripts.  Sadly we just missed a release on CRAN but maybe updating the GitHub repo is good enough for you to test?

**Comment by eitsupi** [comment]
Thank you for your immediate and detailed reply!

> We could possibly turn on `-i` for this scripts. Sadly we just missed a release on CRAN but maybe updating the GitHub repo is good enough for you to test?

Yes, I would like to try it without waiting for the CRAN release.

**Comment by eddelbuettel** [comment]
Could you possibly play with it locally?  I just checked and the shebang line is `#!/usr/bin/env r` (to be more portable).  I seem to recall that there were / are limits as to whether one can (or cannot) add additional flags.

Also, looking at the issue more closely there is indeed 'cruft' in `/tmp`.  Maybe just maybe we can fix that by setting `TMP` or `TEMPDIR` or ... before calling the function from the `remotes` package.  (As opposed to altering how `r` starts and inits itself.)

**Comment by eddelbuettel** [comment]
A simple `r -i -e 'remotes::install_github("user/repot")'` does not fix it either.

I am definitely aware of the issue (as use these littler functions all day long on my machine) as my own /tmp is cluttered.  I think your best immediate fix may be `Rscript` :)    To be continued ...

**Comment by eddelbuettel** [comment]
The fix (in a quick test on the shell) appears to be `mkdir /tmp/foo; export TMP=/tmp/foo` after which all cruft is in `/tmp/foo`.  Better?

**Comment by eitsupi** [comment]
I changed shebang line to `#!/usr/local/bin/r -i`, but it had no effect.
Also, setting the env var `TMP` and `TMPDIR` in the script did not change it.

I'm going to use Rscript for now. Thanks!

**Comment by eddelbuettel** [comment]
> Also, setting the env var TMP and TMPDIR in the script did not change it.

That may have to happen outside of it (i.e. at the Dockerfile level).  The R process initialization, once set, cannot undo it on the fly when `r` is running.

**Comment by eitsupi** [comment]
> 
> 
> > Also, setting the env var TMP and TMPDIR in the script did not change it.
> 
> That may have to happen outside of it (i.e. at the Dockerfile level). The R process initialization, once set, cannot undo it on the fly when `r` is running.

I see. Set `TMP` before running `installGithub.r` workes for me.
But for my current use, I don't have multiple packages I want to install from GitHub, so the Dockerfile may be simpler with using `Rscript -e "remotes::install_github()"`.

**Comment by eddelbuettel** [comment]
My bad -- I forgot we have an explicit -t switch for this!!  Try `#!/usr/local/bin/r -t` instead.

```sh
edd@rob:~$ r --help

Usage: r [options] [-|file]

Launch GNU R to execute the R commands supplied in the specified file, or
from stdin if '-' is used. Suitable for so-called shebang '#!/'-line scripts.

Options:
  -h, --help           Give this help list
      --usage          Give a short usage message
  -V, --version        Show the version number
  -v, --vanilla        Pass the '--vanilla' option to R
  -t, --rtemp          Use per-session temporary directory as R does
  -i, --interactive    Let interactive() return 'true' rather than 'false'
  -q, --quick          Skip autoload / delayed assign of default libraries
  -p, --verbose        Print the value of expressions to the console
  -l, --packages list  Load the R packages from the comma-separated 'list'
  -d, --datastdin      Prepend command to load 'X' as csv from stdin
  -L, --libpath dir    Add directory to library path via '.libPaths(dir)'
  -e, --eval expr      Let R evaluate 'expr'


edd@rob:~$ 
```

The `-t` is what you want here, I think.  (Untested but from wondering and looking at the source...)

**Comment by eitsupi** [comment]
> Try `#!/usr/local/bin/r -t` instead.

Thanks. This is certainly the behavior I wanted!
That seems work like `Rscript -e "remotes::install_github()"`

**Comment by eitsupi** [comment]
@eddelbuettel Does closing this issue mean that the behavior has changed? Or do I need to continue with the solution described in the comments above?

**Comment by eddelbuettel** [comment]
I showed you how you need to invoke it, you showed yourself an alternate. There has been no update since rendering the issue stale so I closed it.

**Comment by eitsupi** [comment]
Thank you for the explanation. I understand now.

**Comment by eddelbuettel** [comment]
I understand it bit you, but it is established (decade-plus ago) and documented (as _e.g._ per the `--help` output) behavior I can't quite flip now without creating havoc in other corners.  The best, really, is to explicitly set the temporary directory.
