### ISSUE TITLE
Order of multiple `--repositories` flags for `install2.r` affects outcome

### ISSUE THREAD

**Issue by pmoris** [eddelbuettel/littler#93]
Let me start with a bit of background on what I'm trying to achieve, you can skip further down to the actual problem I'm running into with the `install2.r` script.

I'm trying to create custom R Docker images by extending the [rocker images](https://github.com/rocker-org/rocker-versioned2) to make my research environment reproducible. In order to make the building of my Dockerfile reproducible as well, I'm using the [RStudio Package Manager (RSPM)](https://packagemanager.rstudio.com/client/#/repos/1/overview) to freeze my packages in time by using a repository URL for a specific date. This works for RSPM's main (all) or CRAN package repository, but things seem to be a bit more tricky for Bioconductor packages.

If I understand things correctly, you can set RSPM as an alternative Bioconductor repository (via `options(BioC_mirror = "https://packagemanager.rstudio.com/bioconductor")`), but the version of a packages that is installed will always be the newest one for the specific version of BiocManager that is installed, rather than being able to pin a specific date via the repo URL. Indeed, when you set the RSPM as the `BioC_mirror` and check the output `BiocManager::repositories()`, before and after up- or downgrading `BiocManager` you will see that the underlying repositories also change.

I've also noticed that when you install Bioconductor packages via either `R -e 'BiocManager::install("package")` or `/usr/local/lib/R/site-library/littler/examples/installBioc.r` package, failed installs (due to mistyped package names, unavailable dependencies, etc.) will not pass a non-zero exit code to the shell. Consequently, Docker builds will continue on their merry way and complete without any errors, even though the contents will not be as expected.

Both of those findings led me to use the following approach in my Dockerfiles: install bioconductor packages via `install2.r` (which by default does not support bioconductor, since it only reads the CRAN entry from `options("repos")`), and explicitly pass all the different bioconductor sub-repositores (as listed by `BiocManager::repositories()`), as well as the CRAN repo (because adding any `-r` flag seems to make `install2.r` forget about the standerd CRAN repo defined by `options("repos")`). This way, I _do_ get a proper exit code when an install fails and my Docker build stops when they encounter an issue.

**However, it seems that the order in which these repositories are passed, affects the outcome. For example, as tested in a rocker/tidyverse docker environment:**

```
$ docker run -it rocker/tidyverse:latest /bin/bash
Unable to find image 'rocker/tidyverse:latest' locally
latest: Pulling from rocker/tidyverse
Digest: sha256:4822761fd1e10029363f85d3322b1c1cf8b3e21a448d68fa2df773b9c39dd654
Status: Downloaded newer image for rocker/tidyverse:latest
root@687831a159d4:/# R

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> options("repos")
$repos
                                                           CRAN
"https://packagemanager.rstudio.com/all/__linux__/focal/latest"

> options("BioC_mirror")
$BioC_mirror
NULL

> BiocManager::repositories()
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://packagemanager.rstudio.com/all/__linux__/focal/latest

                                                       BioCsoft
                  "https://bioconductor.org/packages/3.14/bioc"
                                                        BioCann
       "https://bioconductor.org/packages/3.14/data/annotation"
                                                        BioCexp
       "https://bioconductor.org/packages/3.14/data/experiment"
                                                  BioCworkflows
             "https://bioconductor.org/packages/3.14/workflows"
                                                      BioCbooks
                 "https://bioconductor.org/packages/3.14/books"
                                                           CRAN
"https://packagemanager.rstudio.com/all/__linux__/focal/latest"
> options(BioC_mirror = "https://packagemanager.rstudio.com/bioconductor"
+ )
> options("BioC_mirror")
$BioC_mirror
[1] "https://packagemanager.rstudio.com/bioconductor"

> BiocManager::repositories()
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://packagemanager.rstudio.com/all/__linux__/focal/latest

                                                                       BioCsoft
           "https://packagemanager.rstudio.com/bioconductor/packages/3.14/bioc"
                                                                        BioCann
"https://packagemanager.rstudio.com/bioconductor/packages/3.14/data/annotation"
                                                                        BioCexp
"https://packagemanager.rstudio.com/bioconductor/packages/3.14/data/experiment"
                                                                  BioCworkflows
      "https://packagemanager.rstudio.com/bioconductor/packages/3.14/workflows"
                                                                      BioCbooks
          "https://packagemanager.rstudio.com/bioconductor/packages/3.14/books"
                                                                           CRAN
                "https://packagemanager.rstudio.com/all/__linux__/focal/latest"

>

root@19549bfea339:/# echo $CRAN
https://packagemanager.rstudio.com/all/__linux__/focal/latest

root@687831a159d4:/# BIOC_SOFT="https://packagemanager.rstudio.com/bioconductor/packages/3.14/bioc"
root@687831a159d4:/# BIOC_ANN="https://packagemanager.rstudio.com/bioconductor/packages/3.14/data/annotation"
root@687831a159d4:/# BIOC_EXP="https://packagemanager.rstudio.com/bioconductor/packages/3.14/data/experiment"
root@687831a159d4:/# BIOC_WORKFLOWS="https://packagemanager.rstudio.com/bioconductor/packages/3.14/workflows"
root@687831a159d4:/# BIOC_BOOKS="https://packagemanager.rstudio.com/bioconductor/packages/3.14/books"

root@687831a159d4:/# install2.r --error --skipinstalled -d TRUE -r $CRAN -r $BIOC_SOFT -r $BIOC_ANN biomaRt
Warning: dependencies ‘XML’, ‘mockery’, ‘filelock’, ‘bookdown’, ‘png’, ‘RCurl’ are not available
also installing the dependencies ‘zlibbioc’, ‘GenomeInfoDbData’, ‘XVector’, ‘GenomeInfoDb’, ‘Biostrings’, ‘BiocGenerics’, ‘Biobase’, ‘IRanges’, ‘S4Vectors’, ‘KEGGREST’, ‘AnnotationDbi’, ‘BiocFileCache’, ‘BiocStyle’

trying URL 'https://packagemanager.rstudio.com/bioconductor/packages/3.14/bioc/src/contrib/zlibbioc_1.40.0.tar.gz'
Content type 'application/x-gzip' length 256082 bytes (250 KB)
=======^C

root@687831a159d4:/# install2.r --error --skipinstalled -d TRUE -r $CRAN -r $BIOC_SOFT -r $BIOC_ANN -r $CRAN biomaRt
also installing the dependencies ‘bitops’, ‘zlibbioc’, ‘RCurl’, ‘GenomeInfoDbData’, ‘XVector’, ‘GenomeInfoDb’, ‘png’, ‘Biostrings’, ‘BiocGenerics’, ‘Biobase’, ‘IRanges’, ‘S4Vectors’, ‘KEGGREST’, ‘filelock’, ‘bookdown’, ‘XML’, ‘AnnotationDbi’, ‘BiocFileCache’, ‘BiocStyle’, ‘mockery’

trying URL 'https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/bitops_1.0-7.tar.gz'
^C
Warning message:
package ‘https://packagemanager.rstudio.com/all/__linux__/focal/latest’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

root@687831a159d4:/# install2.r --error --skipinstalled -d TRUE -r $BIOC_SOFT -r $BIOC_ANN -r $CRAN biomaRt
Error: packages ‘https://packagemanager.rstudio.com/bioconductor/packages/3.14/bioc’, ‘biomaRt’ are not available for this version of R

Versions of these packages for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
In addition: Warning message:
packages ‘https://packagemanager.rstudio.com/bioconductor/packages/3.14/bioc’, ‘biomaRt’ are not available for this version of R

Versions of these packages for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

root@687831a159d4:/# install2.r --error --skipinstalled -d TRUE -r $CRAN -r $BIOC_SOFT -r $BIOC_ANN -r $BIOC_EXP -r $BIOC_WORKFLOWS -r $BIOC_BOOKS biomaRt
Warning: dependencies ‘XML’, ‘mockery’, ‘filelock’, ‘bookdown’, ‘png’, ‘RCurl’ are not available
also installing the dependencies ‘zlibbioc’, ‘GenomeInfoDbData’, ‘XVector’, ‘GenomeInfoDb’, ‘Biostrings’, ‘BiocGenerics’, ‘Biobase’, ‘IRanges’, ‘S4Vectors’, ‘KEGGREST’, ‘AnnotationDbi’, ‘BiocFileCache’, ‘BiocStyle’

trying URL 'https://packagemanager.rstudio.com/bioconductor/packages/3.14/bioc/src/contrib/zlibbioc_1.40.0.tar.gz'
Content type 'application/x-gzip' length 256082 bytes (250 KB)
=================^C
```

As you can see, when I add the CRAN repository first, followed by the BioC ones, some CRAN dependencies like XML cannot be found. If I add the CRAN repo a second time, as the last entry, they are found. If I specify the BioC repo first, followed by CRAN, the BioC package itself cannot be found. 

So my questions are:
- Is this behaviour of the order of repos intended and documented somewhere?
- Is my approach of using `install2.r` a good one? Or is there an alternative strategy that does notify me when an bioconductor package install fails inside a Docker build? Can I modify the `installBioc.r` script to do this perhaps? This script does seem to be able to read the current bioconductor repository from `BiocManager::repositories()` (or perhaps it reads `options("BioC_mirror")` and completes this URL with the software/annotation/experiment/etc. sub-repository suffixes?), so I wouldn't need to extract the different BioC repository URLs from the `BiocManager::repositories()` myself.

If can cross-post this issue to either the rocker or the bioconductor github page if you believe they'd get more traction there, just let me know.

**Comment by eddelbuettel** [comment]
I think you may have come to the wrong repo here.  I am just trying to _help_ people working with repos by making scripts in `littler` available.  This started with `install.r`; we later had a need in Rocker to expand on it and added `install2.r`.

Now you are doing something complicated mixing _both_ large scale repo _and_ delivery forms (binary) including a third party.  How any or all of this gets resolved is what `update.packages()` does.

Honestly, `littler` has nothing to do with this in any shape or form. You seem to have an issue with how the upstream repos interact.  That is beyond the scope of `littler` which _merely embeds the R interpretet to let you run simple commands against it_.  

Maybe the BioC community can help, maybe they can't. I hang out in their slack but I do not have seen too much discussion of RSPM there either.

**Comment by eddelbuettel** [comment]
Posting at Rocker will be no different as you'd still talk to me for base Rocker.  Maybe eitsupi can help you with RSPM and BioC, maybe he can't.  I don't see too much BioC discussion there either.

**Comment by pmoris** [comment]
Thanks for the prompt reply!

So if I understand you correctly, the fact that the order in which I pass the different repositories to `install2.r` results in different outcomes, is due to how `update.packages()` tries to resolve everything? If that's the case, then this issue indeed does not belong here.

I will try cross-posting to Rocker regardless and see if eitsupi can offer any insight. In any case, I believe that adding some guidance on the rocker website on how to modify rocker images with bioconductor packages would be helpful to other users as well. Or at least warn them on what to watch out for. Especially considering the fact that rocker/tidyverse comes with BiocManager pre-installed, alongside RSPM repositories. 

I might reach out to Bioconductor as well, because their docker modification instructions also don't mention any caveats (like the error messages not causing builds to stop).

**Comment by eddelbuettel** [comment]
>  the order in which I pass the different repositories to [`.libPaths()`, effectively, -- DE] `install2.r` results in different outcomes,

That's how I understand it based on my quarter century with R and fairly extensive work with repositories.  It is also .... very standard and _e.g._ used with `$PATH`:  "first match wins".  How else could it be done?

I am also not sure how you expect eitsupi to help you.  I think you "simply" have set yourself up for a hard problem (between two repos with know synchronisation issues accross time) which you attempt to constrain further by RSPM date.  It may work, it may not, but `littler` has no dog in the fight.  I'd actually try the BioC lists or slack.  They likely know more.

**Comment by eddelbuettel** [comment]
That said, I don't want to come across as overly negative -- I like what you do here. I simply think it is 'difficult'.  That's all.  Good luck though.

**Comment by pmoris** [comment]
>  How else could it be done?
I've had little experience with repository management, so I wouldn't know. Thanks for the `PATH` comparison though, that makes sense to me! Perhaps adding a warning somewhere that when providing multiple repositories the order is relevant could still be useful to others who'd be surprised by this like myself?

> I am also not sure how you expect eitsupi to help you.
Ah, I thought that was what you were suggesting in your previous message. _"Maybe eitsupi can help you with RSPM and BioC, maybe he can't."_

> which you attempt to constrain further by RSPM date. 
Simply using the default repositories provided by rocker, also leads to a number of problems with installing Bioconductor (or even GitHub) packages, because of the silently failing docker builds. That is not in scope of littler obviously though, but it might be useful to add these things to rocker's guide on modifying images?

**Comment by eddelbuettel** [comment]
Just a thought:  the BioC folks also do containers.  Maybe start with theirs and take their work around dates and releases as a start and see if/how you can add RSPM?
