### ISSUE TITLE
install2.r does not install dependencies from BioConductor

### ISSUE THREAD

**Issue by JulianSpagnuolo** [eddelbuettel/littler#94]
Some packages on CRAN require dependencies that are on BioConductor. It would be really awesome if install2.r could install these deps as well.

**Comment by eddelbuettel** [comment]
AFAICT you can't -- BioConductor is a little different and prefers that you go through their package controlling installation.  

And that is provided by [`installBioc.r`](https://github.com/eddelbuettel/littler/blob/master/inst/examples/installBioc.r)  which is what I use for BioConductor packages.  Please give that a try. I will close this, feel free to reopen if it does not suit your need.

**Comment by nick-youngblut** [comment]
Is there a reason by [installBioc.r](https://github.com/eddelbuettel/littler/blob/master/inst/examples/installBioc.r) isn't listed in the repo README?

**Comment by eddelbuettel** [comment]
I appreciate your enthusiasm for `installBioc.r` but I think filing three distinct issues in the space of minutes is ... wasting my and your time?   

The directory inst/examples/ has _dozens_ of scripts many of which I use daily.  Some are listed in the README, some are not.  _C'est la vie._  We won't / can't list all -- they are after all visible in inst/examples.  Good enough for me.

**Comment by eddelbuettel** [comment]
Sure, we love feedback.  As we respond to every issue, three is a still a little ... unusual.  Ah well, no harm intended, no harm done.
