### ISSUE TITLE
Print error messages to stderr by default

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [eddelbuettel/littler#97]
Rscript prints error messages stderr.

```
$ cat main.R
stop('Error')
$ Rscript  main.R > /dev/null
Error: Error
Execution halted
```

But littler prints error messages to stdout. How to make littler print error messages to stderr instead by default?

```
$ lr -e 'stop()'
Error:
$ lr -e 'stop()' > /dev/null
```

**Comment by prRZ5F4LXZ** [comment]
Yes. I run lr on macOS. Here is the lr version. I don't think it is a bash. Does anybody who also use lr on macOS see the same problem?

```
$ lr --version
r ('littler') version 0.3.15

using GNU R Version 4.0.2 (2020-06-22)

...
```

**Comment by prRZ5F4LXZ** [comment]
Is there any test case that I can run easily on macOS to decipher what is the underlying cause?

**Comment by eddelbuettel** [comment]
I would not know. I don't own any macOS machines.  You will need to debug this at your end.  

I do not see _any_ statement in code enforcing one or the other.  As I said, `stop()` comes from R itself which `littler` just wraps around.  My R on macOS may use `stdout` is not clear to me.  Maybe ask on `r-sig-mac`?

**Comment by eddelbuettel** [comment]
Closing for lack of follow-up / reproducible example.  Please feel free to reopen with additional material.
