### ISSUE TITLE
runtime "error while loading shared libraries: libRblas.so ...."

### ISSUE THREAD

**Issue by barryrowlingson** [eddelbuettel/littler#98]
I've got R compiled from source and installed in /opt/R-4.1.1/

I install.packages("littler") and the exe is built without error. But running it produces:

```
> /opt/R-4.1.1/lib/R/library/littler/bin/r
/opt/R-4.1.1/lib/R/library/littler/bin/r: error while loading shared libraries: libRblas.so: cannot open shared object file: No such file or directory
```

The `gcc` line on build is:
```
gcc -o r -g -O2 -I/opt/R-4.1.1/lib/R/include littler.c -L/usr/local/lib -Wl,--export-dynamic -fopenmp
 -L/usr/local/lib -L/opt/R-4.1.1/lib/R/lib -lR -lpcre2-8 -llzma -lbz2 -lz -lrt -ldl -lm -licuuc -licui18n
 -L/opt/R-4.1.1/lib/R/lib -lRblas -L/opt/R-4.1.1/lib/R/lib -lRlapack -Wl,-rpath,/opt/R-4.1.1/lib/R/lib -Wl,-rpath,/usr/local/lib 
 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/jvm/java-11-openjdk-amd64/lib/server 
 -Wl,-rpath,/opt/R-4.1.1/lib/R/lib -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/lib/x86_64-linux-gnu
 -Wl,-rpath,/usr/lib/jvm/java-11-openjdk-amd64/lib/server -Wl,-rpath,/opt/R-4.1.1/lib/R/lib
 -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/jvm/java-11-openjdk-amd64/lib/server
 -Wl,-rpath,/opt/R-4.1.1/lib/R/lib -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/lib/x86_64-linux-gnu
 -Wl,-rpath,/usr/lib/jvm/java-11-openjdk-amd64/lib/server 
```

`libRblas.so` is in:

```
$ ls /opt/R-4.1.1/lib/R/lib/
libRblas.so  libRlapack.so  libR.so
```
which is the path specified in the `-L` before `-lRblas` in the `gcc` line. Setting LD_LIBRARY_PATH works:

```
$ LD_LIBRARY_PATH=/opt/R-4.1.1/lib/R/lib/ r
message("Working")
Working
```

but shouldn't `r` know where to find it given the options to `gcc`? `libR.so` is found in the same place, but not `libRblas.so` - what's different?

```
$ ldd /opt/R-4.1.1/lib/R/library/littler/bin/r
	linux-vdso.so.1 (0x00007ffc53df1000)
	libR.so => /opt/R-4.1.1/lib/R/lib/libR.so (0x00007f3423755000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3423524000)
	libRblas.so => not found
```

Running `strace` on `r` shows it looking for `libR.so` under `/opt/R-4.1.1` but `libRblas.so` is only looked for under `/lib` and '/usr/lib` locations before giving up. This is the limit of my knowledge of how linux shared library loading works so I'm wondering if you have any ideas what dumb thing I've done this time...

R 4.1.1 on Ubuntu 20.04
littler: Version: 0.3.15

**Comment by eddelbuettel** [comment]
"If you break it you get to keep the pieces."  Non-standard path, non-standard installation options, the works.   

`littler` writes itself a small `Makefile` to build based on some discovery it runs.  It would appear those run afoul at your end.  And I suspect only you can help yourself here.

Also allow me to hint that we offered binaries for Ubuntu for at least a decade, the Rutter PPAs offer both R and `littler` pre-made.   You are free to do your own thing, of course, but if it breaks ... well you know.

**Comment by eddelbuettel** [comment]
And FWIW I never ever build with libRblas.so (which use to be a handicalled subset of BLAS, it is better now) so I would not know.  Maybe R itself sets an rpath for its shared library but not for libRblas.  No idea -- but that is R.   It seems you get by with your chose options if you set LIB_LIBRARY_PATH to your non-standard path.   So I suggest you just do that and close this issue as I do not think we discovered a shortcoming in `littler`.  But I may be missing something so feel free to clue me in.

**Comment by barryrowlingson** [comment]
Seems that on my system when building from source then `--enable-BLAS-shlib` is the default. `./configure --help` is equivocal:

```
--enable-BLAS-shlib     build BLAS into a shared/dynamic library [perhaps]
```
and there's nothing in the output of `./configure` that explains its final decision to enable it. Its listed in "Options enabled:" at the end so one might assume that someone has decided that's the default and its "safe" in some way. 

Configuring with that option explicitly disabled creates an R that happily runs `littler` without any tweaking:

```
./configure --enable-R-shlib  --disable-BLAS-shlib
```

So I think that's a better solution for building R from source for me.

Thanks for the help.

**Comment by eddelbuettel** [comment]
Nice to know you have it sorted out.  

If you have a minute, and mostly to satisfy my own curiousity, can you detail why you need to locally build, and why you don't like any of the existing BLAS/LAPACK libraries?

In the meantime I will close the issue ticket as it really was an R configuration story.

**Comment by barryrowlingson** [comment]
Local build is mostly for two reasons: firstly inertia from when that was the only way, and secondly so I can install on systems I don't have admin rights and therefore can't install with `apt` (although are there user-installable linux binaries now that just go into a user libPath()?). We have some slow sysadmins on our servers. 

Plus I know I'm going to be compiling and installing my own stuff, which means I have to have all the dev tools there and installing R etc from scratch is a good test that they're all present and correct.

I've not specified any BLAS/LAPACK, I'm just hitting the defaults here, assuming they are good enough. If there's an easy way to get +100% performance with a config option, I'm all ears...

**Comment by eddelbuettel** [comment]
Nodding re 'not root', nice alternative to have a directory below which you can write.

I have used the external LAPACK/BLAS on Debian/Ubuntu since the 1990s.  They are good.  You may need to bring your sysadmin a fresh cuppa to get a new package installed to -- I use to favour Atlas, these days I favour OpenBLAS and that is how the package builds.  So for me:

```r
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 21.04

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.13.so
[... stuff omitted ...]
```

and

```sh
ii  libopenblas-dev:amd64                      0.3.13+ds-3                                                          amd64        Optimized BLAS (linear algebra) library (dev, meta)
ii  libopenblas-pthread-dev:amd64              0.3.13+ds-3                                                          amd64        Optimized BLAS (linear algebra) library (dev, pthread)
ii  libopenblas0:amd64                         0.3.13+ds-3                                                          amd64        Optimized BLAS (linear algebra) library (meta)
ii  libopenblas0-pthread:amd64                 0.3.13+ds-3                                                          amd64        Optimized BLAS (linear algebra) library (shared lib, pthread)
```
